### ISSUE TITLE
Suspicious Process Reparenting alerts from Windows Defender

### ISSUE THREAD

**Issue by dflock** [jart/cosmopolitan#1023]
Just updated to cosmos-3.1.3 and our IT dept said that it triggered an alert in Windows Defender: "Suspicious Process Reparenting Detected". This is the command that it flagged:

![image](https://github.com/jart/cosmopolitan/assets/47756/5c26e95e-ef79-4eec-bde0-c518b06f36a5)

"Bash created the process ls by spoofing its parent process"

I'm guessing that this is probably unavoidable and just how this works?

**Comment by jart** [comment]
This is working as intended. On UNIX the execve() system call replaces the current process. To emulate that behavior on WIN32, we use the same technique that the Go programming language uses, which is to pass a special argument to CreateProcess() that spoofs the parent process. The code we use to do that is here:

https://github.com/jart/cosmopolitan/blob/5c358635249616157b1e02c603ceb852dfc33ef7/libc/proc/execve-nt.greg.c#L53-L61

I just scanned the latest cosmos.zip release with Windows Defender and it came up clean. You must have some kind of added restrictions in your corporate security policy. Please ask your IT staff about whitelisting Cosmo programs so that our execve() doesn't raise red flags. At the very least, I'd whitelist the bash binary.

Note: Some of our binaries, e.g. Cosmos GNU Make, are able to avoid calling execve() by using posix_spawn(). That shouldn't need to be whitelisted.
