### ISSUE TITLE
How to speed up the build process  - or -  How to use system tools to build cosmopolitan  ?

### ISSUE THREAD

**Issue by mulle-nat** [jart/cosmopolitan#1090]
cosmopolitan 3.2.4 is quite easy to build and its nice that there are enough headers now (compared to 2.x). But the build process is slow (and weird) for me as a cosmopolitan user (not a cosmopolitan developer). I use cosmopolitan as an alternative C library.

The bottleneck is, that every time I build the cosmopolitan library (and that could be quite often in a day), the `Makefile` downloads the complete set of developer tools! When I do a `clean all` of my project,  there will be an additional 70 MB download... 

If I override the `DOWNLOAD := $(shell build/download-cosmocc.sh $(COSMOCC) 3.2 28b48682595f0f46b45ab381118cdffdabc8fcfa29aa54e301fe6ffe35269f5e)`  statement from the make command line with my own caching downloader, I assume, I can make this faster.  Once I have a cosmopolitan build, the downloaded tools are of no use to me. The next step is to rebuild all my C and Objective-C libraries, with the system `gcc`  and my custom `clang` with cosmopolitan as the SDK. This works fine.

But I wonder: can't I just get by with the system tools to also build cosmopolitan ?  And if yes how ?

> Also, there is an opaque blob in the repository for `make`, you download opaque blobs during the build for `gcc` and friends.  I don't get warm feelings from that..

**Comment by mrdomino** [comment]
Some thoughts.

1. The download can be preserved over clean by moving `.cosmocc` somewhere outside of the repository, e.g. to `/opt/cosmocc`, and symlinking it back in afterwards. Perhaps the download script can be modified to check for this (e.g. look at `${COSMOCC:-/opt/cosmocc}` in the environment and if it exists, use it.)
2. Do you really need to be doing a `clean all` every time? The make dependency setup is supposed to be pretty durable; it should be rare (and a reportable bug) for a clean to be necessary.

**Comment by mrdomino** [comment]
I see, that makes sense. So it's nontrivial to get another volume in there with `cosmocc` in it?

Another way to look at the problem (on our end) would be distfile synchronization — have an option to pass a file path to the zip archive and use that instead of downloading a new one.

I'm sort of intentionally avoiding the question of how to build cosmopolitan against non-cosmo compilers, because I don't think it's really my place to make that judgement. But personally I can see arguments either way. In the direction of not supporting it: cosmopolitan is doing a very different thing from musl. Whereas musl is trying to be a drop-in system libc that builds native binaries on native architectures, cosmopolitan is trying to provide a single interface that works independently of architecture. For that purpose, I think it's actually desirable for the build to be as hermetic and reproducible as possible.

**Comment by mulle-nat** [comment]
I made a few experiments and it turns out that I can't clobber `DOWNLOAD := ...`  with `make DOWNLOAD=`. This would work, if its a regular assignment but `:=` happens too early. Patching it out on the fly with `sed` or something is of course  possible. I just wanted to correct that in my post.

Since the downloader is not downloading anything, if it finds something at `o/cosmocc`, I could put the tools somewhere else in the `PATH`. Still not my favorite option though :wink:

**Comment by jart** [comment]
1. `rm -rf o; make -j32 o//libc` takes 4.7 seconds on my workstation, which has a $568 microprocessor.
2. If the directory `.cosmocc/3.2/` exists then `make` won't download anything, and your build is 100% local. The contents of that folder can be obtained from cosmocc-3.2.zip here https://github.com/jart/cosmopolitan/releases/tag/3.2 and stored on some local HTTP server you control if you want.
3. If you run `mkdir -p .cosmocc/3.2/ && make -j32 TOOLCHAIN=` then Cosmo will build using your system compiler and download nothing. This may or may not work, depending on what compiler and what version of your compiler, and what assembler, and what linker you have installed, and what operating system you're using. You're more than welcome to use this trick, however you should go into it with the expectation that you'll be the one owning it, sending us pull requests to fix it when it breaks, etc.
