### ISSUE TITLE
git in cosmos

### ISSUE THREAD

**Issue by tionis** [jart/cosmopolitan#1116]
Git was once part of the cosmos package with some libexec helpers, but I couldn't find any information why it was removed, so I'm asking here for discoverability.

**Comment by ahgamut** [comment]
It's available here: https://github.com/ahgamut/superconfigure/releases/download/z0.0.34/web.zip

**Comment by tionis** [comment]
Yeah, but it's not on cosmos.pub and regularily updated like the rest.

**Comment by jart** [comment]
Cosmo git is still experimental. You can get it from superconfigure which is a trusted source connected with this project. I don't feel comfortable shipping git in a cosmos release right now because git functioning reliably is of particular importance and some wrinkles are known to exist with it on Windows which I haven't fully vetted yet for the common use cases.
