### ISSUE TITLE
How to build cosmopolitan without downloadimng any extra files?

### ISSUE THREAD

**Issue by yurivict** [jart/cosmopolitan#1117]
I am trying to build on FreeBSD 14, but it downloads some zip file.

How to build cosmopolitan entirely from source?

**Comment by Dessix** [comment]
Building cosmopolitan on Nix is partly blocked by this, which blocks clean integration of APE format into NixOS. This, in turn, blocks writing of a proper solution to Mozilla-Ocho/llamafile#12, which noted it as a Cosmopolitan / APE problem.

On the plus side, the following Nix module can be used to register the `ape` binfmt once the `ape-run` package is made available on the system:
<details>
<summary>
NixOS configuration module for APE binfmt
</summary>

```nix
{ config
, lib
, pkgs
, ape-run
, ...
}:

let
  inherit (lib) types;
  cfg = config.virtualisation.ape;
in {
  options = {
    virtualisation.ape.enable = lib.mkOption {
      type = types.bool;
      default = false;
      description = lib.mdDoc ''
        Whether to enable [Actually Portable Executable](https://justine.lol/ape.html) support.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    boot.binfmt.registrations.ape = {
      interpreter = "${ape-run}/bin/ape";
      magicOrExtension = ''MZqFpD'';
      mask = ''\xff\xff\xff\xff\xff\xff'';
      fixBinary = false;
      matchCredentials = true;
      preserveArgvZero = false;
      wrapInterpreterInShell = false;
    };

    boot.binfmt.registrations.ape-jart = {
      interpreter = "${ape-run}/bin/ape";
      magicOrExtension = ''jartsr'';
      mask = ''\xff\xff\xff\xff\xff\xff'';
      fixBinary = false;
      matchCredentials = true;
      preserveArgvZero = false;
      wrapInterpreterInShell = false;
    };
  };
}
```

Simply set `virtualisation.ape.enable = true;` in `/etc/nixos/configuration.nix` and switch to the configuration.

I use the following definition to cheat for the moment, since this issue is active and unsolved:
```nix
ape-run = (let
    version = "3.3.1";
    apeBinary = fetchurl {
      url = "https://cosmo.zip/pub/cosmos/v/3.3.1/bin/ape-x86_64.elf";
      name = "ape-x86_64.elf";
      hash = "sha256-fBz4sk4bbdatfaOBcEXVgq2hRrTW7AxqRb6oMOOmX00=";
    };
  in runCommand "ape-${version}"
    {
      pname = "ape";
      inherit version;
      meta = {
        description = "Loader for Actually Portable Executable (APE) binfmt";
      };
    }
    ''
      mkdir -p $out/bin
      cp --reflink=auto ${apeBinary} $out/bin/ape
      chmod +x $out/bin/ape
    ''
  );
```
</details>

**Comment by mrdomino** [comment]
@Dessix pardon my ignorance, but how does NixOS handle this with gcc / system libc? Maybe a similar approach can be used.

The download is just providing a bootstrap cosmocc with a known SHA-256 for expedience and build reproducibility. (`build/download-cosmocc.sh` is what is doing it.) If there's some other way that Nix prefers to go about bootstrapping compilers, then that can probably be used instead, at least on that platform.

**Comment by tomberek** [comment]
I've had some luck with using apeloader. Don't use this directly because those hashes will break and we should build these from source, but it gives an idea of how to run ape's in the store without too much extra copying or self-modifying: https://github.com/tomberek/llamafile/blob/master/apeloader-bin.nix

**Comment by mrdomino** [comment]
There isn't really a concept of "other OSes" as far as cosmopolitan is concerned; the binaries it is downloading are the FreeBSD binaries. They just happen to also be the OpenBSD, NetBSD, Linux etc binaries. The idea is that you should get bit-for-bit identical binaries regardless of the platform you build on.

What you need to do is somehow ensure that the bootstrap cosmocc distribution is accessible at build time. I'm not sure what's the best way to do that, but I would recommend trying to follow whatever FreeBSD ports does in other situations - e.g. gcc, clang/llvm, or ghc. It would also be fine to supply the zip it's trying to download as a binary blob; if everything's working properly, the results should be indistinguishable either way.

Somehow or another, you need to come up with a bootstrap cosmocc that you can use to build cosmopolitan (including its own cosmocc.) Once you have that, it's sufficient to make `.cosmocc/$COSMOCC_VERSION` contain that distribution (e.g. by symlinking to it), and then the download will not happen.

**Comment by mrdomino** [comment]
The basic obstacle is just the bootstrapping problem: you are trying to compile a compiler that is meant to be compiled by that compiler. The above-mentioned projects (gcc, llvm, and ghc) all have the same problem, and there are different approaches to solving it. In cosmopolitan's case, the compiler is called cosmocc.

Cosmopolitan's approach to the problem is to say "there is one binary distribution, identified by one SHA-256, that is the correct cosmocc compiler for a given version of cosmopolitan, across every supported platform." So your task is to somehow provide that binary distribution.

If you want, you can bootstrap it yourself — `tool/cosmocc/package.sh` shows how to do that. But you will still need a bootstrap compiler, and you can see that the script fetches a gcc to use.

**Comment by Dessix** [comment]
@mrdomino Nix generally expects you to use one of the preexisting compilers. From what I understand, the initial bootstrap of NixOS itself is a thoroughly complicated but almost entirely deterministic process.

Ideally, rather than relying on a build of itself, built *by* itself, cosmopolitan would have a bootstrapper build that can be assembled by any standard GCC or Clang toolchain- which it could then use to subsequently build its final form.

**Comment by mrdomino** [comment]
@jart any thoughts on this?

**Comment by jart** [comment]
We don't have the resources to support `n` compilers.

**Comment by Dessix** [comment]
`n` compilers is excessive, sure- but bootstrapping from gcc, which in turn can be bootstrapped from an arbitrary, compliant c compiler only requires one bootstrap compiler target.

@mrdomino suggested such a bootstrap mechanism already exists, but my attempt at understanding it collapsed in the self-referential Github-actions schemes of the toolchain dependencies. If something *is* there which allows it to bootstrap from source and a GCC instance, gentoo, bsd, and nix can all use that path.

**Comment by jart** [comment]
GCC needs to be bootstrapped using GCC. Why is it an issue that cosmocc needs to be bootstrapped with cosmocc?
