### ISSUE TITLE
`ape -` without arguments is broken

### ISSUE THREAD

**Issue by mrdomino** [jart/cosmopolitan#1172]
If you just run a binary with no arguments (i.e. `argc == 0`) like `ape - printargs`, when the binary is run, there are no arguments. Okay but follow me. The loader used to edit `argv[0]` to be the name of the binary that was being run.

It still did that in the case when `argc == 0`.

So what was it editing? I guess the sentinel NULL at the end of argv before envp? Anyway, bad stuff. Went away when the loader started passing the executable path via register. Was about to come back in #1170 until 76b1051b648aeb872303209ba3b81f04aa31e45b.

That commit takes the approach of doing a simple bounds check; if `argc == 0`, it does not edit argv, and the binary is on its own. But the edge case still exists: if you invoke an older cosmopolitan binary with `ape -` and no argv, it will have no arguments, and therefore `GetProgramExecutableName` and ZipOS won't work right.

This was always an issue with old loaders and old binaries, going back at least as far as `ape -` did. It is no longer an issue with current loaders and current binaries. But it remains an issue with current loaders and old binaries. If you run into a case where an old binary invoked with no arguments isn't working right, now you know why.

**Comment by mrdomino** [comment]
I’m marking this “won’t fix” but keeping it in the issues page in case someone goes searching for it in the future.

**Comment by mrdomino** [comment]
The way you could fix this, if you wanted to, is to allocate an extra 2 (because of 16-bit alignment) words for the new stack if `argc == 0`, and then later on if you detect that you need to rewrite argv[0], you can move argc and argv back by two, increment argc, set argv[0], and shuffle the last environment variable to first place and do the same for auxv.

This seems like a lot of work and not worth it for such a peculiar edge case.

**Comment by ghaerr** [comment]
> The way you could fix this, if you wanted to

Are you talking about in the loader, before jumping to the executable entry point? In this case, it would seem, that when `argc == 0` SP will be pointing directly at argc (=0), with the next 64-bit word being the start of the NULL terminated environ array, followed the same by AUXV with two NULLs.

Decrement the stack by two 64-bit words, fill in argc & argv, then a quick `MemMove` for the entire environ and AUXV arrays down one word. No need to swap/shuffle env/aux pointers since any pointers will still point to the same original string locations:
```
    uint64_t *sp;   // previously set by OS pointing to argc

    if (!argc) {
        uint64_t *osp = sp;         // old argc
        *--sp = argv0;              // new argv[0]
        *--sp = 1;                  // argc = 1
        int n = 3;                  // precount one env NULL and two aux NULLs
        while (*osp++) n++;         // count env
        while (*osp++) n++;         // count aux
        MemMove(sp+2, sp+3, n * 8); // slide env/aux array down one word
    }
```

**Comment by ghaerr** [comment]
Yeah I guess if we're looking for speed that wouldn't do it. I kind of missed that lol.

**Comment by mrdomino** [comment]
I mean heck it would probably be fine in practice. I just still don't think it's worth it.

**Comment by ghaerr** [comment]
Agreed. Another thought, if you control crt0.S in the executable, would be to just decrement SP once and set a new argc, and use the old spot for argv, no MemMove. The stack would be out of alignment when crt0.S is jumped to.

Then, in crt0.S after copying SP[0] to argc and argv set to SP + 1, execute `and $-16,%rsp`. This aligns the stack frame before calling main. 

 (BTW, this misalignment from the OS can happen in Intel macOS and was fixed in the Cosmo loader with a prior PR of mine fixing a segmentation violation at startup:
```
XnuEntrypoint:
        mov     $_HOSTXNU,%dl                   // xnu's not unix!
ElfEntrypoint:
        mov     %rsp,%rsi                       // save real stack
        andq    $-16,%rsp                       // force SSE alignment
        call    ApeLoader
```
