### ISSUE TITLE
Not working on WSL1

### ISSUE THREAD

**Issue by zyp001a** [jart/cosmopolitan#119]
I run the tutorial and build hello.com, it works on ubuntu and windows 10.
It can execute on windows subsystem for linux(WSL), but print nothing.

My WSL is ubuntu 18.04, Window 10 version is 19041.804
My WSL is not WSL2

**Comment by jart** [comment]
Could you run the following command?

    cat /proc/sys/fs/binfmt_misc/status

If that's the case can you try this and let us know if it works?

    sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"

**Comment by alisonatwork** [comment]
You might want to have a look at my bug report https://github.com/jart/cosmopolitan/issues/76 - I struggled with the same problem before switching my installs to WSL2 kernel.

Regarding the binfmt_misc, I found that on WSL1 it did not matter if I registered APE magic number, it still failed to run correctly. I think WSL1 has some magic it always tries to run MZ executables native instead of through the WSL layer, which perhaps confuses the Cosmopolitan runtime. It might be safer to disabling binfmt_misc altogether. But even then, I was still not able to get the binaries running properly, so eventually I gave up and just switched kernels to WSL2.

**Comment by jart** [comment]
Thanks for helping our friend @alisonatwork. It sounds like the solution is to upgrade to WSL2.

**Comment by zyp001a** [comment]
`cat /proc/sys/fs/binfmt_misc/status` 
return "enabled"
`sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register`
not works.

**Comment by alisonatwork** [comment]
Hi @zyp001a - if you are interested in tracking down the cause of this issue, I do suggest reading my linked bug report, because I experienced similar problems and couldn't figure it out.

One thing you can do is disable binfmt. You can do this by running `echo 0 > /proc/sys/fs/binfmt_misc/status`. After you do that when you `cat` it, it should say `disabled`.

The other thing you can do is instead of running `hello.com`, run `hello.com.dbg` - this will force it into Linux mode, so you can be sure that WSL is not somehow hijacking and trying to run it as a Windows executable.

Now, for me, even running the Linux version kept throwing a mysterious error inside the assembly code. If you are good at `gdb` maybe you can find out why or where it is happening. My guess is that something inside Cosmopolitan is detecting Windows, even though we are Linux and doing the wrong thing (or vice versa), but it could also just be a limitation of WSL1. Switch kernel to WSL2 should work.

**Comment by jart** [comment]
One thing you might be able to do is:

```
gdb hello.com -ex 'add-symbol-file hello.com.dbg 0x401000'
```

That might give us a better idea of what's happening. If a fix is possible I'd be interested in doing it since there isn't a clear signal from Microsoft that they're officially EOL'ing WSL1 and their documentation site recommends it as the first step of installation.

**Comment by zyp001a** [comment]
> Hi @zyp001a - if you are interested in tracking down the cause of this issue, I do suggest reading my linked bug report, because I experienced similar problems and couldn't figure it out.
> 
> One thing you can do is disable binfmt. You can do this by running `echo 0 > /proc/sys/fs/binfmt_misc/status`. After you do that when you `cat` it, it should say `disabled`.
> 
> The other thing you can do is instead of running `hello.com`, run `hello.com.dbg` - this will force it into Linux mode, so you can be sure that WSL is not somehow hijacking and trying to run it as a Windows executable.
> 
> Now, for me, even running the Linux version kept throwing a mysterious error inside the assembly code. If you are good at `gdb` maybe you can find out why or where it is happening. My guess is that something inside Cosmopolitan is detecting Windows, even though we are Linux and doing the wrong thing (or vice versa), but it could also just be a limitation of WSL1. Switch kernel to WSL2 should work.

after `echo 0 > /proc/sys/fs/binfmt_misc/status`, binfmt is disabled. I recompile hello.com, still print nothing; hello.com.dbg print nothing.

I plan switch to WSL2 in June, this year.

**Comment by zyp001a** [comment]
> One thing you might be able to do is:
> 
> ```
> gdb hello.com -ex 'add-symbol-file hello.com.dbg 0x401000'
> ```
> 
> That might give us a better idea of what's happening. If a fix is possible I'd be interested in doing that since there isn't a clear signal from Microsoft that they're officially EOL'ing WSL1 and their documentation site recommends it as the first step of installation.

`$ gdb hello.com -ex 'add-symbol-file hello.com.dbg 0x401000'
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...

warning: A handler for the OS ABI "FreeBSD" is not built into this configuration
of GDB.  Attempting to continue with the default i386:x86-64 settings.

Reading symbols from hello.com...(no debugging symbols found)...done.
add symbol table from file "hello.com.dbg" at
        .text_addr = 0x401000
(y or n) y
Reading symbols from hello.com.dbg...done.
(gdb)
`

**Comment by jart** [comment]
Thanks for posting the GDB output. Sadly it seems the failure is happening at a lower level than it's able to debug. This would likely need an expert to take a look, like someone from the WSL dev team.

**Comment by zyp001a** [comment]
> Thanks for posting the GDB output. Sadly it seems the failure is happening at a lower level than it's able to debug. This would likely need an expert to take a look, like someone from the WSL dev team.

These gdb output for hello.com.dbg may helps.
```
c$ gdb ./hello.com.dbg
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hello.com.dbg...done.
(gdb) starti
Starting program: /home/zyp/testc/hello.com.dbg

Program stopped.
_start () at libc/crt/crt.S:32
32      libc/crt/crt.S: No such file or directory.
(gdb)
```
