### ISSUE TITLE
cosmo.zip offiline?

### ISSUE THREAD

**Issue by santagada** [jart/cosmopolitan#1192]
I see some links in https://justine.lol/cosmo3/ point to https://cosmo.zip which to me give this error if I try to access it:

"
An error occurred during a connection to cosmo.zip. PR_CONNECT_RESET_ERROR

Error code: PR_CONNECT_RESET_ERROR
"

**Comment by santagada** [comment]
We found the issue, a Palo Alto firewall thinks cosmo.zip is a parked domain (which it isn't). Maybe try contacting them to update their database?
https://live.paloaltonetworks.com/t5/community-blogs/new-dns-security-category-parked/ba-p/345465
I'll be trying to convince our network operators to override it too :). Sorry for thinking it was a real problem.

**Comment by jart** [comment]
I just spoke with someone at Palo Alto Networks and have filed a change request with https://urlfiltering.paloaltonetworks.com/ in which they've been provided with all the information they need. I'm confident this should satisfactorily resolve your issue. Thank you for filing this report, since it's likely to help other users too.
