### ISSUE TITLE
Support UEFI

### ISSUE THREAD

**Issue by Ronsor** [jart/cosmopolitan#12]
As the title says, support running as a (U)EFI application.

**Comment by jart** [comment]
It's possible to change the `v_ntsubsystem` symbol to the number that's needed for the UEFI subsystem.

https://github.com/jart/cosmopolitan/blob/de09bec215675e9b0beb722df89c6f794da74f3f/ape/ape.S#L785

However it's worth noting that doing so would prevent the binary from being able to run on Windows. That's why the BIOS bootup process is preferred.

**Comment by jart** [comment]
Closing this out as won't fix since having out-of-the-box UEFI support means trading away Windows support, and BIOS works fine.

**Comment by paulreimer** [comment]
In the long haul, I hope more cool things will be done with UEFI + bare-metal, than with Windows. Perhaps there is space for another flavour of cosmopolitan?

**Comment by jart** [comment]
What's UEFI able to do? I'm largely uneducated about its capabilities. The main thing I've heard about it so far is you need to get Microsoft to digitally sign your program if you want to share it with other people. Who could have imagined ten years ago that the Linux Kernel of the future would ship as a .exe file? But no matter. 

I'm totally down for making it possible with APE to flip a bit that turns off Windows support and turns on UEFI. For example we could make that tunable with `-DSUPPORT_VECTOR=...` described here: https://justine.lol/cosmopolitan/howfat.html

**Comment by Ronsor** [comment]
The UEFI specification is over 1500 pages long, but in short, it includes a lot of OS-like functionality:

* Driver loading
* File I/O (FILE_PROTOCOL)
* Networking
* Framebuffer Graphics (GRAPHICS_OUTPUT_PROTOCOL)
* Sometimes WiFi...

**Comment by jart** [comment]
What are the highlights? What is UEFI able to do that BIOS can't? Aside from having the ability to keep working on machines that have chosen to block anything that isn't a signed UEFI binary. What is the process for obtaining authorization from Microsoft that would enable me to distribute Actually Portable Executables on the Cosmopolitan website which use UEFI?

**Comment by paulreimer** [comment]
(I preface this with the note that I'm only able to glimpse at the power of this library/APE. I might be vastly misunderstanding my own use-case.)

For my current homelab experiment, I would like to netboot a fleet of edge hardware with APEs / bare-metal, and the hardware I currently use only has a UEFI loader. My idea of "portable" here is Linux (dev) + bare-metal (prod).

**Comment by jart** [comment]
That sounds like a good use case. So far bare metal is the least developed part of Cosmopolitan. The only driver it supports at the moment is serial stdio. I've wanted to add something like an e1000 network driver for quite some time. Would that work with your hardware?

**Comment by paulreimer** [comment]
Indeed simple network servers is what I have in mind. e1000 seems most reasonable, I can get my hardware aligned with that.

If I ever move on beyond servers I would be interested in framebuffer and audio subsystems, next. I'd like to explore the "cross-metal"(?) workflow first, and even UEFI + serial would give me lots to play with for now.

**Comment by jart** [comment]
It looks like it can be done:

![image](https://user-images.githubusercontent.com/49262/108643841-2c5eeb80-7461-11eb-809a-131086c4498d.png)

Let me see if I can get o//tool/viz/deathstar.com running on UEFI in which case I'll push this change right away along with further instructions.

**Comment by jart** [comment]
I've just added UEFI support in https://github.com/jart/cosmopolitan/commit/537c21338bc3722218a55766d8adb2908d8df987 and it exceeds feature parity with BIOS support that Cosmopolitan also currently provides. Developing for UEFI is so easy since it's basically already an operating system. Here's the documentation I've written on how to use it:

https://github.com/jart/cosmopolitan/blob/537c21338bc3722218a55766d8adb2908d8df987/libc/runtime/efimain.c#L25-L58

I'm going to focus on getting you memory mappings next. Since you might not be able to use sockets but I want you to at least be able to use malloc. I'll update the bug tracker when that happens. You can reach out to me via email too.

**Comment by paulreimer** [comment]
It works! Thank you so much!

I'm so excited for sockets, but adding support for malloc would let me play with more existing cool things. How very cosmopolitan!

**Comment by paulreimer** [comment]
I am currently using [pixiecore](https://github.com/danderson/netboot/tree/master/pixiecore) to (ad-hoc / run-and-gun) "deploy" this to netbooting machines; this can be run from anywhere in the network:
```
sudo pixiecore boot ./o/examples/hello.com
```

**Comment by piranna** [comment]
> Since you might not be able to use sockets but I want you to at least be able to use malloc.

UEFI doesn't have sockets in the POSIX style, but you can have networking :-)

https://edk2-docs.gitbook.io/edk-ii-uefi-driver-writer-s-guide/25_network_driver_design_guidelines/253_simple_network_protocol_implementations
