### ISSUE TITLE
Compiling Jainja JVM

### ISSUE THREAD

**Issue by glegris** [jart/cosmopolitan#121]
Hi,

Thanks for your amazing work !

I had a try with [Jainja ](http://jainja.thenesis.org/)(I'm the author), a JVM (interpreter only) with the same focus on portability. 

I made it work after fixing a small issue: a name collision in some source files with the "hidden" define in cosmopolitan.h 

An issue still remains: at compile time, the detected platform is unix, Hence when I run the JVM on Windows, file paths are not handled correctly (path separator should be "\\" instead of "/"). I have to find a way to detect platform at runtime. Any idea ?

**Comment by jart** [comment]
Am I understanding correctly that you compiled the Java Virtual Machine with Cosmopolitan? Could you show us how you did that? Because that's amazing.

The i/o system calls automatically turn backslash into forward slash on Windows. You likely encountered an issue with absolute paths. Cosmopolitan is agnostic to those and simply hands it off to the underlying system. Right now there's no intent to wrap windows with a virtual posix file system like cygwin does. Our model is lightweight and works seamlessly if a program sticks to the directory tree in which it's spawned. 

Lastly note Cosmopolitan is inspired by UNIX and chooses to support and conform to POSIX conventions whenever possible, so we have more time to be wildly unconventional at executable formats. So we've been careful to not claim to be UNIX even though Java thinks it quacks enough like UNIX.

**Comment by glegris** [comment]
Yes, the JVM was compiled with Cosmopolitan ! You get a Java 5 JVM with a subset of the Java standard library. 

Threads are implemented in the VM itself, so native multi-threading is not required. IO are implemented by using non-blocking functions of the C standard library and POSIX library.

For paths, I think it's better to stick to the current directory as you suggest.

I'll commit clean stuff and build instructions in a day or two. There are too many hacks to be able to reproduce the build easily for now.

I attach a zip file containing some demos (the headless UI demo doesn't work on Windows yet, I don't know why):
[jainja-cosmopolitan.zip](https://github.com/jart/cosmopolitan/files/6119355/jainja-cosmopolitan.zip)

**Comment by jart** [comment]
Please don't post binaries on this issue tracker. I was hoping you'd share the build script and necessary changes in the form of a GitHub project. Also, how did you obtain the Java 1.5 source code? Isn't that only permitted for non-commercial research? I looked at the OpenJDK repository and it only goes as far back as Java 7 it seems.

**Comment by glegris** [comment]
Sorry for the binaries, doing things after midnight makes me lose my lucidity sometimes :sweat_smile: (Note to me: sleep more)

I'm doing my best to post code on GitHub ASAP.

As you may know OpenJDK is born in 2008. It starts with OpenJDK 6 (most known as IcedTea6). 

There are other free implementation of the Java Standard library:
- GNU Classpath (since 1998, GPL with linking exception): Java 5 implementation currently with some Java 6 features
- Apache Harmony (2006-2011, Apache license, 97% Java 6) which was used by Android until 2016. After that, Android (Nougat) switched to some parts of OpenJDK.

[Jainja ](http://jainja.thenesis.org) library is not based on OpenJDK but uses a mix of GNU Classpath and Harmony, It's licensed under GPL with a linking exception (like OpenJDK)

**Comment by jart** [comment]
I'm sorry I can't provide support for building personal projects.
