### ISSUE TITLE
It's magic... can we depend on it to keep working?

### ISSUE THREAD

**Issue by Choons** [jart/cosmopolitan#126]
I'm truly amazed by APE/cosmo/redbean. I confess to not really understanding how it works-- there is deep code mastery at work that is beyond my experience as an independent app developer. It seems like a paradigm shift with huge disruptive potential. That makes me wonder if Microsoft, Apple, Google, even Canonical will embrace or oppose it? Will they view it as an exploit or an innovation? Either way, can they stop it? Since I don't work so close to the metal, I can't evaluate that properly like I'd like to. Can mere mortal developers depend on cosmopolitan to continue working for the foreseeable future (say at least 2-3 years)? It's so amazing, will "they" let us have it?

**Comment by jart** [comment]
We have no control over what the major platforms do because we're not them. There's nothing magical about what this project does. They're just programs. This project has sought to distribute with openness and transparency. You are responsible for how you choose to distribute your own work. I would recommend following the same model.

**Comment by Choons** [comment]
Quite true. Just from a technical standpoint, is APE/Cosmopolitan something that major platforms can stop easily, or would it require them to make significant changes (i.e. not worth it)? Not trying to be negative-- I really want to use cosmo, but I hate when I get used to working with a tool only to have it suddenly stop working.

**Comment by jart** [comment]
Once again, we have no control over what the major platforms do because we're not them. This project has sought to rely on stable kernel interfaces. For example on Windows we link things like KERNEL32 and we don't use things like NTDLL. In the cases where we need to use it, we do so in a way that respects Microsoft's recommendations.
