### ISSUE TITLE
Missing math function definitions

### ISSUE THREAD

**Issue by dosisod** [jart/cosmopolitan#127]
These functions declared in `libc/math.h` do not have definitions:

* fdim
* fdimf
* fdiml
* fma
* fmaf
* fmal
* nexttoward
* nexttowardl
* nexttowardf
* erfcf
* erff
* remquo
* remquof
* remquol
* frexpf
* frexpl

I could probably take care of the `fdim` and `remquo` functions myself, will put in a PR soonish.

**Comment by jart** [comment]
I would recommend copying the implementations from the Musl Libc codebase, so long we preserve the copyright notices. For example: 

https://github.com/jart/cosmopolitan/blob/6388ef21f8ecfc91139a92077970ba1e7f37e607/libc/tinymath/erf.c#L1-L39

**Comment by dosisod** [comment]
Added all the functions except for `fma`, `fmaf`, and `fmal`, since they rely on floating point environments (`fenv.h`).

**Comment by jart** [comment]
Thanks for doing this. Musl fma() says it needs the environment but that line should be safe to delete since it got refactored a few years ago to use integer arithmetic. The same isn't the case for fmaf() and fmal() so I'm fine setting those two aside for the time being if you don't need them. There's also a treasure trove of functions in complex.h but the standard doesn't strictly require them.
