### ISSUE TITLE
timingsafe_memcmp for crypto

### ISSUE THREAD

**Issue by rurban** [jart/cosmopolitan#13]
Excellent collection of extensions.
I'm just missing more crypto stuff from the BSD's.

And maybe better UTF-8 string support, instead of the dreaded wchar standard, which doesn't even know about normalization, thus cannot do string cmp, searching for strings in unicode.

**Comment by jart** [comment]
Cosmopolitan now includes `timingsafe_memcmp`. Enjoy!

Cosmopolitan uses the C locale with UTF-8. So I'm not quite sure what you're requesting w.r.t. collation and normalization, which is a task that's largely governed by policy table restrictions that might be more appropriately left to something like libicu.

One thing Cosmo does implement quite well, however, is support for East Asian Monospace Widths, since that frequently comes up in my work. For example, the `printf()` family of functions will actually take it into consideration if you were to do something like `printf("%8s\n", "😀")`.

**Comment by rurban** [comment]
Thanks.

I disagree with bloatware libicu. String support needs to be in the standard IMHO, and is pretty simple. I do support wcsnorm and wcsfc in safeclib, but nobody should use wcs anymore.

The Asian width support also, as u8glen, btw. (Graphical length). For u8 I'm adding identifier support for restrictions to public names (usernames, paths, symbols, ...), with the u8i prefix.

**Comment by jart** [comment]
I feel the same way. You've got a nice library. Out of curiosity what's your view on ASAN? 

https://github.com/jart/cosmopolitan/blob/1df136323be2ae806f5e7ef8879fcdfd60506062/libc/log/asan.c#L39-L66

**Comment by rurban** [comment]
Brilliant. I love Kosta
