### ISSUE TITLE
using shared libraries

### ISSUE THREAD

**Issue by dvtsantsynger** [jart/cosmopolitan#137]
Сan dlopen be used and is it cross-platform? Thanks!!

**Comment by jart** [comment]
Right now `dlopen` is implemented as a stub that returns an error. I'd love to support dynamic shared objects but sadly they're deeply intertwined with the implementation details of the distro in question. On Linux distros, for example, all the `.so` files link the platform-specific C library, which would clash with Cosmopolitan. In the future, we might be able to offer dynamic code loading by a different means, but it's unlikely we'll ever be able to support seamless integration with the platform-specific methodology of dynamic code loading on each platform.

**Comment by pkulchenko** [comment]
Since loading of dynamic libraries was discussed in #215, I thought I'd also link the discussion on this topic that happened in [#97](https://github.com/jart/cosmopolitan/issues/97#issuecomment-874415031). I still think that generating a library in a platform-portable (cosmopolitan-based) format is the best option, as it then can be handled by the cosmopolitan loader to load.

**Comment by pkulchenko** [comment]
A couple of links that may be helpful for the implementation:
- [Detailed documentation about Windows executable from MemoryModule](https://github.com/pkulchenko/MemoryModule/tree/master/doc)
- [POSIX equivalent of Windows DLL import libraries](https://github.com/yugr/Implib.so)
- [SO question about loading symbols into a specific namespace (dlmopen)](https://stackoverflow.com/a/33612509/1442917)
