### ISSUE TITLE
Optionally skip overwriting the APE binary file header

### ISSUE THREAD

**Issue by niutech** [jart/cosmopolitan#146]
Could you please provide an optional flag for `gcc` at compile time to skip overwriting the APE binary file header upon first run? The problem is that after the first run, the APE binary is no longer portable and cannot be redistributed without restoring the original header. I would like to keep the file intact so that after testing I could send it to my teammates using multiple OS-es.
A workaround is to make a file read-only or copy the original file before the first run, but people often forget to do this in advance.
Thanks!

**Comment by jart** [comment]
Sure I can add a compile flag for that.

**Comment by jart** [comment]
I've updated the website so you now have a choice between `ape.o` and `ape-no-modify-self.o` which may be downloaded from https://justine.lol/cosmopolitan/download.html Please note, this alternative APE bootloader has its caveats of its own, which are documented by the following comment. Feedback is welcome. Enjoy!

https://github.com/jart/cosmopolitan/blob/da8a08fd58324a87f6ac673b7774512e861fe477/ape/ape.S#L549-L561

**Comment by niutech** [comment]
Thanks a lot!

**Comment by mnhrdt** [comment]
> Feedback is welcome.

This commit is a great step towards a cosmopolitan-based unix distro (with an arbitrary, possibly time-varying kernel!).  Imagine that each executable on /bin/ and /usr/bin is an APE, owned by root.  The APE_NO_MODIFY_SELF option is necessary so that unprivileged users can run the programs without modifying them.  But it needs to be robust to any name clashes, as for example the "sed" executable can be run by several scripts simultaneously by several users.  Would you accept a patch that builds the name of the temporary file in a robust way? (and, optionally, inside /dev/shm if available)

**Comment by jart** [comment]
I'm totally open to doing what I can do to support distributors. Let's discuss the idea before you commit time to writing a patch.

Right now the current behavior, on most systems, if you put an alternative APE binary in a system folder, is as follows:

```
[jart@freebsd ~]$ sudo cp smoke-nms.com /usr/local/bin/
[jart@freebsd ~]$ smoke-nms.com; echo $?
0
[jart@freebsd ~]$ tree -u /tmp/usr
/tmp/usr
└── [jart    ]  local
    └── [jart    ]  bin
        └── [jart    ]  smoke-nms.com

2 directories, 1 file
```

What XNU does is it defines TMPDIR to some user-specific `/var/folders/hv/FOO` path upon login. So instead of going in `/tmp/local/bin/smake-nms.com` it will go in `/var/folders/hv/FOO/usr/local/bin/smoke-nms.com`. The behavior of Cosmo and XNU is inspired by the following POSIX recommendation:

> The /tmp directory is retained in POSIX.1-2017 to accommodate historical
> applications that assume its availability. Implementations are encouraged
> to provide suitable directory names in the environment variable TMPDIR and
> applications are encouraged to use the contents of TMPDIR for creating
> temporary files. —Quoth IEEE 1003.1-2017 §A.10.1

Systemd goes it own way, and that's unlikely to change, so I'd be open to merging a patch that changes `${TMPDIR:-/tmp}` to `${TMPDIR:-${XDG_RUNTIME_DIR:-/tmp}}` assuming there's no harm in doing that.

But let's assume you choose to stick with /tmp by default. Here are some of the options on the table. First, you can prepopulate system dirs with the sticky bit so there's no directory clashes.

```sh
sudo mkdir -pm 01777 /tmp/{bin,usr/{bin,local/bin}}
```

Another option is to have the system reserve those directories for itself, where the administrator or distributor prepopulates them manually.

```sh
# be sure to update cron tmp cleanup script!
sudo mkdir -pm 0755 /tmp/{bin,usr/{bin,local/bin}}
for f in /tmp/{bin,usr/{bin,local/bin}}/*.com; do sudo $f --ape-init; done
```

I'd be open to merging a patch to support a flag like that. Anything is on the table. Let me know your thoughts!

**Comment by jart** [comment]
> But it needs to be robust to any name clashes, as for example the "sed" executable can be run by several scripts simultaneously by several users.

Concerning this, what the embedded script currently does is:

```
mkdir -p dir || exit
cp dir/exe /tmp/dir/exe.$$ || exit
mv /tmp/dir/exe.$$ /tmp/dir/exe
/tmp/dir/exe
```

By putting the PID of the shell in the path, we safeguard against unintentional file name collisions. So that should address the sed concern. In that case the main concern becomes intermediate directory ownership, as discussed by my previous comment.

If the concern is that a user might intentionally try to create collisions, we could make the code a bit less elegant by using tools to generate paths that are more difficult to predict, but I'd ask anyone with those requirements to first consider the alternative of prepopulating system paths, as described above.
