### ISSUE TITLE
consts.sh lacks / wrong

### ISSUE THREAD

**Issue by nuclight** [jart/cosmopolitan#17]
E.g. FD_SETSIZE on Windows is 64

**Comment by jart** [comment]
It's not correct, but it's not not wrong. See the "forced consensus" comment here:

https://github.com/jart/cosmopolitan/blob/0e85b136ae1beb0d2bb7fd77ea9b5527ca1ca497/libc/sysv/consts.sh#L2098

Plus the comment on the declaration here:

https://github.com/jart/cosmopolitan/blob/0e85b136ae1beb0d2bb7fd77ea9b5527ca1ca497/libc/sock/select.h#L6

And the number 64 is hard-coded here:

https://github.com/jart/cosmopolitan/blob/0e85b136ae1beb0d2bb7fd77ea9b5527ca1ca497/libc/sock/select-nt.c#L56

FD_SETSIZE is frequently used to declare data structures, so making it symbolic would break a lot of code. On the other hand, there's no harm done on Windows if an array ends up being longer than needed. Microsoft thinks 64 file handles ought to be enough for anyone, and we agree with Microsoft, since Cosmopolitan users know that if you want a wicked fast 10k+ socket server, then there's no operating system better than Linux or FreeBSD which are built to serve and fully supported too by Cosmopolitan out of the box for free.
