### ISSUE TITLE
Redbean build in WSL2 on Win10 generates asan binaries even in non-debug configuration

### ISSUE THREAD

**Issue by pkulchenko** [jart/cosmopolitan#188]
I mentioned this in https://github.com/jart/cosmopolitan/issues/97#issuecomment-856468516 and thought that I was doing something wrong, as I couldn't run the default build of redbean on win8 (it failed with the message "error: asan binaries require windows10").

I rebuilt redbean from scratch using `make MODE=rel o/rel/tool/net/redbean.com` command, which should *not* include asan binaries (based on my reading of the makefile), but the generated file still seems to include it, as it throws the same error about "asan binaries".

How do I generate a Windows build that doesn't include address sanitizer checks?

**Comment by jart** [comment]
That's due to this line which I had for debugging purposes, but forgot to remove before the 1.0 release.

https://github.com/jart/cosmopolitan/blob/248c6d54bbbfccf18271a96db55193ec1a945f5d/tool/net/redbean.c#L2320

I'll be removing it presently. For more context, we do basically that for the various system calls like `writev()` but it's always intended to be placed behind an `IsAsan()` check so it gets DCE'd in non-DBG mode.
