### ISSUE TITLE
Clarify x86_64 only in README

### ISSUE THREAD

**Issue by elmeyer** [jart/cosmopolitan#192]
Echoing @dumblob's sentiment in https://github.com/jart/cosmopolitan/issues/73#issuecomment-787517296, I find it insufficiently clear from reading the README that Cosmopolitan Libc only works on x86_64 at this time. I suggest to add a clear note to that effect as early as possible in the README.

If you want me to prepare a PR for this, I will gladly do so.

**Comment by jart** [comment]
The encoding of programs is an implementation detail. APE binaries are designed to work on non-x86 systems that have qemu installed, which can do the dynamic code translation, similar to how the JVM needs to be installed in order to do the dynamic code translation from Java byte code to host machine code. The README focuses on the things Cosmopolitan does the best. If you feel like any claims that have been made are false, then let me know, and I'll reopen this issue.
