### ISSUE TITLE
Make assimilation optional

### ISSUE THREAD

**Issue by mcandre** [jart/cosmopolitan#236]
Hi,

I really like the project concept by the way! This has much potential to streamline portable software development.

Say, would it be possible to make the assimilation phase optional? I don't want my binaries to self modify.

I also don't want the hassle of handling my binaries with surgical gloves during packaging. It is common to run an integration test step on newly compiled binaries, just before packaging. But right now, the way Cosmopolitan is written, unfortunately you can't test your app binaries that way.

I would go so far as suggesting to disable assimilation by default. But if this can be a configuration option, then I would also be satisfied.

**Comment by pkulchenko** [comment]
@mcandre, can you elaborate what you mean by the assimilation phase? Also, why can't you test the binaries during integration tests? Is that because the header would need to be modified on Linux?

**Comment by jart** [comment]
You can use `ape-no-modify-self.o` rather than `ape.o`. See #146. This carries caveats of its own. It goes slower. There's system administration considerations. Alternatively you might want to consider copying the binary before CI testing it. That's what I would recommend. Since the non-self-modifying binaries aren't as good. It's worth adding the copy command to your CI config since that means your end-users will get a higher quality finished product.

**Comment by mcandre** [comment]
Just for one example, AV doesn't particularly like self-modifying binaries. It's artificially more difficult to manage security allowlists and blocklists when the binary doesn't have a consistent hash.

Thank you for the suggestion of targeting a different object file, I can try that.

**Comment by jart** [comment]
The binaries don't need to self-modify on Windows.
