### ISSUE TITLE
sysv2nt fails for floats

### ISSUE THREAD

**Issue by jacereda** [jart/cosmopolitan#302]
I've spent quite a while trying to figure out why the OpenGL test I'm using was working properly on Linux but failed on Windows. Looks like `glUniform2f` doesn't work properly and I just resorted to using `glUniform2fv` instead. Probably, floats aren't passed the same way in both ABIs.

**Comment by jart** [comment]
I'm going to close this out since I'm not sure if there's anything we can do with the current one-size-fits-all abstractions (i.e. __sysv2nt and __nt2sysv) and the thunks will need to be written manually. Thanks for documenting which ones need it. That information will be useful if we can update `libc/nt/master.sh` to take care of the process of making opengl32.dll available via the core libc.
