### ISSUE TITLE
Executable file runs only once on Linux

### ISSUE THREAD

**Issue by vshymanskyy** [jart/cosmopolitan#32]
So I've successfully built `Wasm3` (a fast WebAssembly interpreter) with Cosmopolitan, and it runs fine.
But i cannot run it multiple times. The executable gets modified whenever I run it.
![image](https://user-images.githubusercontent.com/1506708/105784175-f1ac8500-5f80-11eb-8ed1-6ae845d95f0e.png)

Binary files (original/modified), please compare:
[wasm3_binaries.zip](https://github.com/jart/cosmopolitan/files/5870464/wasm3_binaries.zip)

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, Ubuntu Linux

**Comment by jart** [comment]
That's exciting to hear! Let me know if there's anything I can do to support your effort.

The reason why that isn't working is because wasm3.com became an ELF binary after the first run. Are you using zsh? There's a known issue with zsh. I've been meaning to upstream a patch. If you want a command that consistently works, try this:

```sh
master jart@nightmare:~/cosmo$ sh -c './hello.com'
hello world
master jart@nightmare:~/cosmo$ sh -c './hello.com'
hello world
```

Regarding self modification, that's currently part of the design. We do things that way because it's significantly faster than copying the whole executable and re-running it. Only the first 64-bytes of the header is modified. It's totally reversible. It's our equivalent to an installer. It's currently the fastest and simplest. It's going to get even better over time. What it looks like:

```sh
master jart@nightmare:~/cosmo$ bf wasm3.orig.com | head -n3
MZqFpD=‘◙  ► °       ☺ ◘@           JT                      ê○  
▓@δ δ¶ÉÉδ♠Hâ∞◘1╥╜  δ♣Θ9◄  ⁿ┐ p1╔Ä┴·Ä╫ë╠√♫▼Φ  ^üεm ╕ ♦PP•1λ╣ ☻≤ñΩ
ä@  Ä┘╣ 0╕ ☺Ä└1└1λ≤¬Ç·@t‼Φ  •░☺1╔0÷┐(☺ΦS Ou·┐@2½æ½Æ½î└½ΩGE  SR┤◘
master jart@nightmare:~/cosmo$ bf wasm3.modified.com | head -n3
⌂ELF☻☺☺○        ☻ > ☺   ô◄@     Ç◘                  @ 8 ♦       
▓@δ δ¶ÉÉδ♠Hâ∞◘1╥╜  δ♣Θ9◄  ⁿ┐ p1╔Ä┴·Ä╫ë╠√♫▼Φ  ^üεm ╕ ♦PP•1λ╣ ☻≤ñΩ
ä@  Ä┘╣ 0╕ ☺Ä└1└1λ≤¬Ç·@t‼Φ  •░☺1╔0÷┐(☺ΦS Ou·┐@2½æ½Æ½î└½ΩGE  SR┤◘
```

The code that does that exists here:

https://github.com/jart/cosmopolitan/blob/45b72485ad102206574629cf278199d050fa7bf7/ape/ape.S#L447-L469

You'll also be pleased to know that a whole bunch of bugs got fixed today. See https://github.com/jart/cosmopolitan/commit/45b72485ad102206574629cf278199d050fa7bf7 which is a huge milestone.

**Comment by jart** [comment]
Update: I've written a patch for zsh so that it conforms to the new POSIX requirements. See https://github.com/jart/zsh/commit/94a4bc14bb2e415ec3d10cf716512bd3e0d99f48 which was just sent off to the zsh-workers mailing list and should be upstreamed soon. I would recommend building zsh locally so you can just use the normal `./hello.com` syntax.

**Comment by vshymanskyy** [comment]
@jart Thanks for the detailed explanation. The project is awesome!

The minimal build of Wasm3 kind of works, however still doesn't pass the WASM specification tests. Will be working on it.
Also, when I try to build the WASI module, I get a bunch of errors.

Also wondering if clang is capable of producing APEs.

I'll comment on this ticket regarding any progress.  Thanks much!

**Comment by jart** [comment]
Those specification tests would be a great way to help iron out any bugs in Cosmopolitan's C library implementation, which isn't as mature as Glibc or Musl. You do however have me here to support you each step along the way.

Cosmopolitan C source code is written to be compatible with Clang. So you can absolutely use it as your compiler. The [build/compile](https://github.com/jart/cosmopolitan/blob/master/build/compile) frontend script smooths out a lot of the differences in terms of GCC vs. Clang build flags. Two things worth noting though: (1) I haven't used Clang in month, (2) llvm-as and llvm-lld aren't supported since they lack features cosmo needs, which is why the script passes flags like `-fno-integrated-as`.

Since you might encounter pain helping to debug Cosmopolitan, here are some tips that will make your life easier!

## Function Tracing

You can pass the `--ftrace` flag to any binary that's built in default mode. This causes the binary to rewrite itself in memory so that the wide nops at the start of each function get turned into function calls that print the function name. For example:

```sh
master jart@nightmare:~/cosmo$ make -j12 o//examples/echo.com
OBJCOPY        o//examples/echo.com
master jart@nightmare:~/cosmo$ o//examples/echo.com hi --ftrace
+           sigprocmask
+           fstat
+             __isfdkind
+           __cxa_atexit
+   main
+     strcmp
+     fputs
+       strlen
+       __fwritebuf
+         write
+           writev
hi
+     __cxa_finalize
+       fflush
master jart@nightmare:~/cosmo$
```

## Crash Reporting

If you call `showcrashreports` from your main function, e.g. 

```c
int main() {
  showcrashreports();
  // ...
}
```

Then it'll automatically attach GDB when a crash happens. If it can't find gdb then it'll print a backtrace. If it can't find `addr2line` then it'll use a built-in symbol backtrace. If it can't find the concomitant .com.dbg binary then it'll print a numeric backtrace.

![image](https://user-images.githubusercontent.com/49262/105825504-86f54c80-5f74-11eb-90f6-f23c12b44b8e.png)

**Comment by vshymanskyy** [comment]
`Wasm3.com` now passes all of the tests on Linux:

```sh
./run-spec-test.py --exec "../platforms/cosmopolitan/wasm3.com --repl"
...
=======================
 17526/17526 tests OK
 (235 tests skipped)
=======================
```

Will try it on windows later.
After adding it to Github Actions, found that gcc 7.5.0 doesn't work:
```log
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
Building Wasm3...
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
/usr/bin/ld.bfd: cosmopolitan/crt.o: unable to initialize decompress status for section .debug_aranges
cosmopolitan/crt.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
```
This was easily fixed by updating to `ubuntu-20.04` env.

Next issue. When I enable WASI module, I get:
```log
cosmopolitan/ape.o: in function `pcread':
ape/ape.S:360:(.head+0x518): relocation truncated to fit: R_X86_64_32 against `_edata'+ffffffffffd00000
ape/ape.S:360:(.head+0x51c): relocation truncated to fit: R_X86_64_32 against `_end'+ffffffffffd00000
cosmopolitan/ape.o:(.pe.header+0x50): relocation truncated to fit: R_X86_64_32 against `_end'+ffffffffffc00000
cosmopolitan/ape.o:(.pe.header+0xe8): relocation truncated to fit: R_X86_64_32 against `idata.iat'+ffffffffffc00000
cosmopolitan/ape.o:(.pe.sections+0x34): relocation truncated to fit: R_X86_64_32 against `.Lape.ram.rva'
cosmopolitan/cosmopolitan.a(ExitProcess.o):(.idata.ro.idt.2.kernel32[kernel32]+0x10): relocation truncated to fit: R_X86_64_32 against `idata.iat.kernel32'+ffffffffffc00000
collect2: error: ld returned 1 exit status
```

**Comment by vshymanskyy** [comment]
@jart BTW, it would be nice if you could "Publish a release" on github, this way my CI workflow wouldn't have to download it from your website every time.

**Comment by vshymanskyy** [comment]
Just switched gcc->clang (with the same options)  and it works well on Linux.
There are some minor floating point precision issues for some reason, in `floor`, `ceil`, `trunc`.
![image](https://user-images.githubusercontent.com/1506708/105990591-611e9380-60ab-11eb-8490-ac6e2aff3b93.png)

**Comment by vshymanskyy** [comment]
@jart  OK, here's how to reproduce the WASI build problem:
```sh
git clone https://github.com/wasm3/wasm3.git --depth 1
cd wasm3/cd wasm3/platforms/cosmopolitan
# in build.sh, add "-Dd_m3HasWASI" to EXTRA_FLAGS
./build.sh
...
...
...
cosmopolitan/ape.o: in function `pcread':
ape/ape.S:360:(.head+0x518): relocation truncated to fit: R_X86_64_32 against `_edata'+ffffffffffd00000
ape/ape.S:360:(.head+0x51c): relocation truncated to fit: R_X86_64_32 against `_end'+ffffffffffd00000
cosmopolitan/ape.o:(.pe.header+0x50): relocation truncated to fit: R_X86_64_32 against `_end'+ffffffffffc00000
cosmopolitan/ape.o:(.pe.header+0xe8): relocation truncated to fit: R_X86_64_32 against `idata.iat'+ffffffffffc00000
cosmopolitan/ape.o:(.pe.sections+0x34): relocation truncated to fit: R_X86_64_32 against `.Lape.ram.rva'
cosmopolitan/cosmopolitan.a(ExitProcess.o):(.idata.ro.idt.2.kernel32[kernel32]+0x10): relocation truncated to fit: R_X86_64_32 against `idata.iat.kernel32'+ffffffffffc00000
```

**Comment by jart** [comment]
Wow I didn't know .debug_aranges was being compressed. Thanks for that. I intend to write a test that automates ssh'ing into RedHat 5.0 and builds a binary using gcc 4.2.1.

The "relocation truncated to fit" error is probably happening because you're not passing `-fno-pie -no-pie` to gcc. I've seen that error pop up before. It's difficult to troubleshoot because the binutils error message for it isn't helpful. I'm going to see if I can make that go away entirely when the linker is run in PIE mode. Those flags should work in the meantime.

Having a release would be a good idea. I will update this issue as soon as one is uploaded to GitHub. Until then, you may use all the bandwidth you need.

**Comment by vshymanskyy** [comment]
@jart I do pass `no-pie` options: https://github.com/wasm3/wasm3/blob/b081a707da6db1fc9f8c0c4e97406fd912320b06/platforms/cosmopolitan/build.sh#L28

**Comment by vshymanskyy** [comment]
@jart Thanks for your PR!
We have now **the most universal WebAssembly runtime** in form of **the most universal executable format**:
![image](https://user-images.githubusercontent.com/1506708/106105571-ddb57e80-614c-11eb-9adb-feeffbb326e5.png)

:partying_face:  :exploding_head:

**Comment by jart** [comment]
That's awesome to hear! Also wow re: all tests passing on the first shot. All we needed to patch was a build script.

I've posted a [v0.1 release](https://github.com/jart/cosmopolitan/releases/tag/0.1) on GitHub, [the website](https://justine.lol/cosmopolitan/download.html) is updated, and it's been [shared on Hacker News](https://news.ycombinator.com/item?id=25952540). I hope it's ok that I gave your project a shout-out in the release notes. I think what you're doing is cool and I'm glad Cosmopolitan has had an enabling impact. Any language author who chooses to adopt Cosmopolitan is going to find themselves gaining an edge that's traditionally been very difficult to obtain.

**Comment by vshymanskyy** [comment]
Congrats with the release! 😊

**Comment by vshymanskyy** [comment]
@jart Is there any way to increase the stack size on Windows?

**Comment by jart** [comment]
Absolutely. How much stack do you need? I set it to the same size Google uses for its production services which is 64kb. However I can easily imagine Microsoft making that difficult in practice.

**Comment by jart** [comment]
It's now increased to what I believe should be a more conventional value. I used the same values that CMD.EXE uses. I've also pushed a new release for you. https://github.com/jart/cosmopolitan/releases/tag/0.1.2 Enjoy!

**Comment by vshymanskyy** [comment]
This is much much better. Thanks!
We can pass Spec Tests under Wine64 now:
https://github.com/wasm3/wasm3/runs/1798349094

WASI tests also show some promising results on Windows (bu not everything is working yet). I'll create separate tickets on specific issues.
Thanks again!

**Comment by jart** [comment]
Oh wow I hadn't tried running it in WINE before. Do you know what the minimum version of WINE is that works? I tried WINE 4.0 which came out in 2019 and noticed it didn't implement APIs Microsoft introduced in 2006 like CreateFileMappingNumaW. Is WINE really that far behind?

**Comment by vshymanskyy** [comment]
I'm using `wine-5.0 (Ubuntu 5.0-3ubuntu1)`, a stock `wine64` Ubuntu package.
So far, I see  very consistent results with native windows execution (i.e. same tests are failing, etc.).

**Comment by jart** [comment]
If you have a quick list of functions in Cosmopolitan you suspect might have issues, feel free to name them and I can start writing tests for them right now.

**Comment by vshymanskyy** [comment]
Currently `wasi_unstable.fd_fdstat_get` implementation doesn't work in multiple scenarios.
In Wasm3, it's a bare bones implementation that uses `fcntl(fd, F_GETFL)`and `fstat(fd, &stat)`.
Wasm3 is capable of tracing execution as well, so I can run the same binary natively on linux/windows (or in wine) and compare the difference.

**Comment by jart** [comment]
I improved the F_GETFL / F_SETFL implementation to bring it closer to POSIX. Cosmo at the moment does an unfancy 1:1 mapping with Windows i/o routines. That makes it a great fit for applications that do conventional i/o workflows like open + read + write + close. It currently doesn't polyfill some of the more subtle behaviors, such as being able to poll stdin and a socket at the same time. The most fancy thing Cosmopolitan does at the moment is vendor wepoll for excellent epoll support. Although I'd still recommend just using fork() with readv() + writev().
