### ISSUE TITLE
Honeybadger image alpha fix

### ISSUE THREAD

**Issue by nicholatian** [jart/cosmopolitan#33]
Not sure where you keep the website and such maintained, but I noticed the honeybadger had some tearing at the edges due to the lack of a full 8-bit alpha channel. The PNG is 8-bit indexed, so I took it into Photoshop and fixed the edges, saving it as a 24-bit PNG. The size difference is less than double, but it’s still only 14 KB so I figured it’s still plenty small enough to be worth changing.
![diff](https://cdn2.arqadium.com/f/f085c51fb1db40f6b861a5eb84a3fd54/unknown.png)

[here](https://cdn2.arqadium.com/f/ff33bedc9ce24171b0952a9ef5e9ade5/unknown.png) is the new PNG.

**Comment by jart** [comment]
Thanks Alexander. Your photoshop-fu is pretty good. I didn't realize that saving as PNG-8 caused transparency tearing. I have a vector version of the honey badger so I scaled a new PNG-24 from that. After running it through `optipng` it turned out to be only 11kb. Here's a 1920x986 version which is surprisingly enough only 20kb:

![image](https://user-images.githubusercontent.com/49262/106093208-b62acb80-60e4-11eb-99d1-b1b0ec2004da.png)

Think I should set up a CafePress and start selling Cosmopolitan honey badger swag?
