### ISSUE TITLE
asset should be readable by user or group, not just others

### ISSUE THREAD

**Issue by setop** [jart/cosmopolitan#335]
https://github.com/jart/cosmopolitan/blob/d6a039821f927cc81b71e11f21599ff93e1fed62/tool/net/redbean.c#L6203

I would have put `if ((m = GetMode(a)) & 0444) {` instead.

It shooted me in the foot as I had a file in `rw-------` and got `403 Forbidden`.

**Comment by pkulchenko** [comment]
@setop, thank you for the report; I submitted a PR in #336.

**Comment by jart** [comment]
Thanks for the report. One surprising thing about zip files is they may contain unix chmod bits the same way the file system does. When you use InfoZip it actually copies the chmod bits from your file system into your redbean. Since redbean can serve from both zip and the file system, it treats chmod bits the same way. Just like nginx and friends, redbean won't serve a file that isn't world readable, in the interest of erring on the side of caution. I think we can do a better job documenting this and adding warnings that will help make this gotcha clear for folks who want public visibility.
