### ISSUE TITLE
windows build disabled and broken

### ISSUE THREAD

**Issue by agreppin** [jart/cosmopolitan#371]
Hi,

Your last commit [0cb6b6f](https://github.com/jart/cosmopolitan/commit/0cb6b6ff4b34a3503cd899ccbb12538a58d73b49) just broke the HOSTS win7 win10, who where commented in the Makefile.
The errors related to winerr.greg.c and some other one.

Just to let you know ...

update:
win7 win10 removed in commit [b45d50](https://github.com/jart/cosmopolitan/tree/b45d50b6902fe695fd6607cd9fa0b2187ceaf666)

**Comment by jart** [comment]
Thanks for bringing it to our attention. I just ran some local tests and it looks like it was a temporary regression, since I'm not able to reproduce it. Let us know if you're still encountering this issue and I'll reopen. New nightly available at https://justine.lol/cosmopolitan/cosmopolitan.zip and please keep following git! Thanks for using Cosmo.

**Comment by agreppin** [comment]
well, I can reproduce this bug if you want, but I have others things to solve ATM
