### ISSUE TITLE
Is it possible to use this with existing static binaries? I'm having trouble understanding the format

### ISSUE THREAD

**Issue by maniyar1** [jart/cosmopolitan#377]
Hello, I know this is a bit of a weird question but I wasn't sure where to ask, and I apologize if it's a bit basic. I'm trying to get an actual portable executable but of, for example a Go program. If I understand the format correctly it should be possible to compile a static binary for each platform and then use the PE/thompson shell trick to execute the right one when the program runs? But I'm having trouble with understanding how the PE/thompson shell trick itself works. I read the actually portable executable page a few times and tried to get through [ape.S](https://raw.githubusercontent.com/jart/cosmopolitan/1.0/ape/ape.S) but im still not exactly solid. Could someone maybe re-explain/point me to a file/give a minimal PE/Thompson shell example? I'm terribly sorry for the inconvenience, and thank you for any help in advance.

**Comment by ghaerr** [comment]
Hello @maniyar1,

There is a lot going on under the hood when it comes to how APE portable executables work, but I'll take a pass at giving you an overview.

An actually portable executable file is at least four things at once, depending on what program is looking at it: for Linux, BSDs and macOS, its a (self modifying) shell script. For Windows, its an MZ-header old-style DOS executable, and for PC hardware boot loaders, it's a valid boot block. And for zip/gzip programs, its a set of arbitrary disk files, all zipped up. This single simultaneous format has been carefully crafted, needless to say.

When a Linux, BSD or macOS operating system is requested to run an APE file (by convention named something.com) , the kernel looks to see whether the requested file has its special magic numbers for native execution. Since the APE file doesn't match any, the kernel rejects direct execution of the binary, which causes the shell itself to further inspect the file, to see whether the file is a shell script. (Sometimes the kernel or system loader itself does this rather than the shell).

The further process of determining the next action for a possible shell script execution next involves checking for a two-character "shebang" sequence at the start of the file - "#!", which then signifies the proper interpreter to execute the file. However, no systems actually require the shebang, and in the APE case, since the .com file is marked executable, the shell itself (or sometimes the kernel loader which loads and runs another shell) starts interpreting the file directly, as sequence of shell commands, a line at a time.

So for Linux, BSDs and macOS, the .com file itself is executed as a shell script. Lets take a look at the start of it, by opening it with any editor:
```
MZqFpD='
^@^@^P^@ø^@^@^@^@^@^@^@^A^@^H@^@^@^@^@^@^@^@^@^@^@^@JT^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^P^K^@^@²@ë^@ë^T<90><90>ë^FH<83>ì^H1Ò½^@^@ë^Eé¡^P^@^@ü^O^_<87>>à¿^@p1É<8e>Áú<8e>×<89>Ìû^N^_è^@^@^<81>îr^@¸^@^BPP^G1ÿ¹^@^Bó¤^O^_<87>Òÿê<8e> ^@^@<8e>Ù¹^@^[¸P^@<8e>À1À1ÿóª<80>ú@t^Sè^U^@^G°^A1É0ö¿ ^@èH^@OuúêH%^@^@SR´^HÍ^Sr,<88>Ï<80>ç?<80>áÀÐÁÐÁ<86>Í^^^F^_1ö<8e>Æ¾^P^U<87>÷¥¥¥¥¥¤^_<93>«<91>«<92>«Xª<92>[ÃZ<80>ò<80>1ÀÍ^Sr÷ëÁPQ<86>ÍÐÉÐÉ^HÁ1Û°^A´^BÍ^SYXr^]<8c>Æ<83>Æ <8e>ÆþÀ:^F^\^Uv^M°^AþÆ:6 ^Uv^C0öAÃP1ÀÍ^SXëÅ<89>þ¬<84>Àt    »^G^@´^NÍ^PëòÃW¿µ$èèÿ_èäÿ¿½$èÞÿó<90>ëü¹^D^@¾^@^D­<85>Àt^KQV<97>¾Ì$è^E^@^YâîÃ<89>ú<85>Òt^TRV1É±^C^AÊ¬^^L<80>îZ¬îBIyúÃ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Uª'
#'"
o="$(command -v "$0")"
type ape-loader >/dev/null 2>&1 && exec ape-loader "$o" "$@"
if [ -d /Applications ]; then
dd if="$o" of="$o" bs=8 skip="     397" count="      87" conv=notrunc 2>/dev/null
elif exec 7<> "$o"; then
printf '\177ELF\2\1\1\011\0\0\0\0\0\0\0\0\2\0\076\0\1\0\0\0\373\020\100\000\000\000\000\000\000\012\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0\0\0\0\100\0\070\0\004\000\0\0\000\000\000\000' >&7
exec 7<&-
else
exit 121
fi
exec "$0" "$@"
R=$?

if [ $R -eq 126 ] && [ "$(uname -m)" != x86_64 ]; then
if Q="$(command -v qemu-x86_64)"; then
exec "$Q" "$o" "$@"
else
echo error: need qemu-x86_64 >&2
fi
elif [ $R -eq 127 ]; then
  exec "$o" "$@"
fi
exit $R
error: ^@^M
```

The first line `MZqFpD='...'` is very tricky: it sets the shell script variable to what seems to be an arbitrary bunch of binary data. This is allowed, since the specification allows for shell scripts to contain binary data if within a quoted variable string. In fact, this first line simultaneously provides the magic MZ signature for the aforementioned Windows MZ executables, along with the important locations for the MZ loader to work, as well as allowing direct execution (starting with the MZ sequence itself as 8086 real mode instructions) by a boot loader. More on all that later. 

For the Linux/BSD/macOS shell interpreting the shell script, it just sets an (unused) variable, and the script execution continues with the next statement, which is a comment:
```
#'"
```
This is more trick stuff, required for other operating environments. Since its a comment, execution continues with the next line:
```
o="$(command -v "$0")"
```
Uses the bash builtin 'command -v' to set the variable 'o' to a single word that can be used to invoke this shell script itself (needed later).
```
type ape-loader >/dev/null 2>&1 && exec ape-loader "$o" "$@"
```
Uses bash builtin 'type' command to determine if "ape-loader" exists, and if so, execute "ape-loader" on the shell script and arguments, if present (usually not present).
```
if [ -d /Applications ]; then
dd if="$o" of="$o" bs=8 skip="     397" count="      87" conv=notrunc 2>/dev/null
```
Checks if the directory /Applications is present (this occurs on macOS only) and executes a `dd` command to overwrite the currently running shell script with a mach-o binary header.
```
elif exec 7<> "$o"; then
printf '\177ELF\2\1\1\011\0\0\0\0\0\0\0\0\2\0\076\0\1\0\0\0\373\020\100\000\000\000\000\000\000\012\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0\0\0\0\100\0\070\0\004\000\0\0\000\000\000\000' >&7
exec 7<&-
```
Finally (for Linux and BSDs), uses the builtin 'exec <>' command to open the current shell script for reading and writing, then executes the external 'printf' program to replace the currently executing shell script with an ELF header, and exec's it (again), closing file descriptor 7.

To fully understand this, consult the [bash reference manual](https://www.gnu.org/software/bash/manual/bash.html#Bash-Builtins).

Thus, for the Linux/BSD/macOS cases, the shell script itself is replaced with (yet another) carefully crafted section of the .com file itself, which just happens to work perfectly for that system's kernel loader (since the magic numbers now match, and the kernel loads the executable normally).

The shell script itself terminates running with the 'exec' builtin, and all subsequent data within the shell script is either ELF or mach-o executable binary data, or the remaining contents of an included zip file. Cosmopolitan's libc is written in such a way such that the 'open' system call can be redirected to read the APE file (as a zip file) to gain access to other included data. Pretty nifty!

Thank you!

**Comment by jart** [comment]
Thanks for helping our friend @ghaerr 

See also:

https://github.com/jart/cosmopolitan/blob/1ff1854107a5f4c57a4492d0460d2b4578c1f3ad/ape/ape.lds#L19-L174

Hope it helps!

**Comment by maniyar1** [comment]
Hello, thank you so much to everyone, I never expected such a kind and thorough response, I sent this to a few friends and we concluded something along the lines of "this is one of the nicest things I've read on Github", so even beyond the technical work I truly hope you continue to foster this community, very much appreciated :).
