### ISSUE TITLE
Recommend function-like macros and semicolon use with macros

### ISSUE THREAD

**Issue by nicholatian** [jart/cosmopolitan#39]
This I recommend from Jonathan Baccara’s Fluent C++ [blog post about the subject](https://www.fluentcpp.com/2019/05/28/better-macros-better-flags/). I am aware that Cosmo is not exactly an “old codebase”, but this is still great practise for its hygiene, and will help others in the future who may hack onto or extend it.

**Comment by jart** [comment]
Thanks for the suggestion. I gave it a read. Cosmopolitan is already doing most of the things he suggests. For example, the most complicated macro magic in this codebase is the following file:

https://github.com/jart/cosmopolitan/blob/cbfd4ccd1e26c0c93c7d2422d7645855affeba51/libc/nexgen32e/x86feature.h#L10-L19
https://github.com/jart/cosmopolitan/blob/cbfd4ccd1e26c0c93c7d2422d7645855affeba51/libc/nexgen32e/x86feature.h#L225-L234

We don't need function-like macros since parameter stuffing ensures there's an error if a parameter is undefined:

```
examples/wut.c:14:1: error: macro "__X86_HAVE" requires 5 arguments, but only 1 given
   14 |   if (X86_HAVE(LOL)) {
      | ^ ~~~~~
```

I like the way the C preprocessor works. Undefined tokens expanding to empty string isn't a problem. For example:

```c
#if (__GNUC__ + 0) * 100 + (__GNUC_MINOR__ + 0) >= 402
// ....
#endif
```

Will evaluate as the following expression if certain parts are undefined:

```c
#if (+0) * 100 + (+0) >= 402
// ....
#endif
```

Thereby avoiding the need for definedness checks.
