### ISSUE TITLE
zip error: Zip file structure invalid (redbean-1.5.com.dbg)

### ISSUE THREAD

**Issue by olastor** [jart/cosmopolitan#397]
I am trying to add files to the debug version of redbean, but it does not work.

```bash
wget https://redbean.dev/redbean-1.5.com.dbg
chmod +x redbean-1.5.com.dbg
echo '<b>hello</b>' >hello.html
zip redbean-1.5.com.dbg hello.html # (bash or zsh)
```

results in

```
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (redbean-1.5.com.dbg)
```

- `uname -a`: `Linux fedora 5.16.11-100.fc34.x86_64 #1 SMP PREEMPT Wed Feb 23 18:04:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- zip version: `This is Zip 3.0 (July 5th 2008), by Info-ZIP.`

Am I missing something?

**Comment by dbready** [comment]
Also broken for me. Interestingly, the non-debug build works as expected.

```
wget https://redbean.dev/redbean-1.5.com
chmod +x redbean-1.5.com
echo '<b>hello</b>' >hello.html
zip redbean-1.5.com hello.html # (bash or zsh)
./redbean-1.5.com
```

**Comment by olastor** [comment]
@jart For me the same error (with ".dbg" only) still appears when I build from the latest master.

**Comment by jart** [comment]
I see now. While the .com.dbg file should run, it absolutely can't be modified by InfoZIP or any tool other than the Makefile build. But that's OK since we're phasing out the need for .com.dbg in redbean. 

Firstly, if your goal is to have debugging symbols for backtraces, then you'll be pleased to hear that redbean (at head) now includes a `.symtab` file inside the .com zip.

Secondly, if your goal is to have a platform-local ELF file, then there's two things you can do with the .com file instead:

1. Delete the `/.ape` file from inside the ZIP. Then your binary will assimilate.
2. Build with `make -j8 MODE=tinylinux` or `MODE=optlinux`

Going to close this out since editing .com.dbg isn't supported.
