### ISSUE TITLE
APE: brk address is too high for qemu

### ISSUE THREAD

**Issue by easyaspi314** [jart/cosmopolitan#399]
The brk() heap starts at `0x100080000000`.

While this is fine on native x86_64, this caused mmap() to fail on qemu-x86_64 on AArch64 because it has a smaller 39-bit address space.

This might also fail on some ancient pre-2007 x86_64 processors with a 40-bit address space.

**Comment by jart** [comment]
We need the high addresses in order to use ASAN. That assumption is baked quite deeply.

We use 32-bit addresses on Windows 7. But we're able to detect Windows 7. I don't know how we would detect qemu aarch64. Consider using Bochs instead to emulate. Bochs will actually emulate the the full address space.

In the future we'll have blinkenlights running on other architectures, as described by the APE blog post. I wish that we could help you for the time being. Please continue to follow the project for status updates. I'm going to close this out since I'm not sure how to make it actionable.
