### ISSUE TITLE
Signals, errno and some "constants" as real constants

### ISSUE THREAD

**Issue by dinosaure** [jart/cosmopolitan#401]
I'm not really aware about how `cosmopolitan` handles that but I try to make an OCaml distribution with `cosmopolitan` as the underlying layer of the _caml runtime_  as we already did for Solo5/MirageOS. However, I got some troubles mainly about constants. An usual design in OCaml is to _map_ constants with their real C values _via_ an array as you can see here:

https://github.com/ocaml/ocaml/blob/ec01245b61e5f41608986cfb11ee010a5f96ac0b/runtime/signals.c#L356-L369

Unfortunately, such design requires that a signal, in my example, must be a constant. It seems that, in `cosmopolitan`, it was not the case:
```c
#ifdef __ASSEMBLER__
/* clang-format off */
#define SYMBOLIC(NAME) NAME(%rip)
#define LITERALLY(NAME) $NAME
/* clang-format on */
#else
#define SYMBOLIC(NAME) NAME
#define LITERALLY(NAME) NAME
#endif

#define SIGUSR1   SYMBOLIC(SIGUSR1)
```

I'm not a C expert so I can not figure out a middle solution without any changes on both sides (`cosmopolitan` and OCaml). Currently, to hot-fix this situation, I decided to `#undef` some signals and some constants (such as `O_TRUNC`) to be able to compile at least, the _caml runtime_:

https://github.com/dinosaure/esperanto/blob/7f928bd67c7d979dab5c9ccf4c572720693c8243/toolchain/include/cosmopolitan/esperanto.h

By this way, even if we have some warning, I can fully compile the OCaml compiler and its runtime and use it then to compile some OCaml program. Most of them, as far as they don't want to create a new file 🙂 , work (on Windows and Linux at least)! But I really would like to go further and find a good solution for both worlds.

The problem, of course, becomes harder when we try to compile `unix.cmxa` (the Unix module in OCaml) which deeply use such design (specially about error codes). The error given by the C compiler when we want to compile OCaml is:
```
/home/dinosaure/.opam/4.14.0/bin/../include/x86_64-esperanto-none-static/cosmopolitan.h:30018:33: error: initializer element is not constant
30018 | #define O_CREAT        SYMBOLIC(O_CREAT)
      |                                 ^~~~~~~
```

**Comment by dinosaure** [comment]
When I see [`./libc/sysv/consts.sh`](https://github.com/jart/cosmopolitan/blob/master/libc/sysv/consts.sh), I can understand why these values are "not" constants. Due to the fact that at the beginning of the program, it seems that `ape.lds` chooses how to execute the program, I believe that at this moment, you correctly set these values (like `O_TRUNC`) corresponding to which host system wants to run the Cosmopolitan's program.

A possible solution will be to compile the caml runtime as I did (with fake values) and, as you do, let the program to to self-modify these values when the program is run for the first time. I clearly don't know how to do that - and I really can not figure out how to do that due to the fact that these arrays (which use constants) are mostly `static`...

**Comment by ahgamut** [comment]
@dinosaure I have seen something similar with global `static const` arrays that require the `errno` values: the error that would appear when compiling [the code in above link](https://github.com/ocaml/ocaml/blob/ec01245b61e5f41608986cfb11ee010a5f96ac0b/runtime/signals.c#L356-L369) would be something like `initializer element is not constant`.

The fix is declare the static array with zeroed-out values, and then write a small function that fills/copies the correct values during initialization:

You can see this done with [`quickjs`](https://github.com/jart/cosmopolitan/commit/8f52c0d7734de16e664e5c4e67e97ffd1a50c3b7) and the [`faulthandler.c` in Python3.6](https://github.com/jart/cosmopolitan/pull/235/commits/b3b538780a67e9ac0e510f59e53505a9ad731925#diff-8828bfa668176929b9b79c0ea1e910bdc147cf04725aa1cc05690abad3ff3aa4) (search for `Static_assert`).

Rough outline of the change you would need to make in the [`runtime/signals.c`](https://github.com/ocaml/ocaml/blob/ec01245b61e5f41608986cfb11ee010a5f96ac0b/runtime/signals.c#L356-L369):

```
static int posix_signals[28];

void _init_posix_signals()
{
int tmp_posix_signals[] = {
  SIGABRT, SIGALRM, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGKILL, SIGPIPE,
  SIGQUIT, SIGSEGV, SIGTERM, SIGUSR1, SIGUSR2, SIGCHLD, SIGCONT,
  SIGSTOP, SIGTSTP, SIGTTIN, SIGTTOU, SIGVTALRM, SIGPROF, SIGBUS,
  SIGPOLL, SIGSYS, SIGTRAP, SIGURG, SIGXCPU, SIGXFSZ
};
 _Static_assert(sizeof(posix_signals) == sizeof(tmp_posix_signals), "alloc error");
    memcpy(posix_signals, tmp_posix_signals, sizeof(tmp_posix_signals));
}
```

and then call the `_init_posix_signals` at the start of `caml_install_signal_handler` or wherever the respective module/function is initialized.
