### ISSUE TITLE
`getcontext` (and others) on Windows

### ISSUE THREAD

**Issue by dinosaure** [jart/cosmopolitan#413]
Hi, currently I try to use Cosmopolitan for OCaml (see [Esperanto][esperanto]). One requirement for the OCaml ecosystem is the `pthread` library. I did the choice to use [`pth`][pth] which seems pretty portable to have concurrency and let the user to use threads in OCaml. Everything works for Linux and, I believe, BSD platforms but I got an issue on Windows.

Indeed, when I try to run a simple code like `cat` in OCaml with concurrency, `pth` uses `getcontext` (and others) to do the concurrency:
[see this C code](https://github.com/dinosaure/esperanto/blob/328db680a060e9020fc9dc68c4ff65cafa208db9/pth/pth_mctx.c#L163-L164). However, on Windows, this call seems to return an error. I don't really know if it's intended or not and I would like to know if I'm wrong (and Cosmopolitan does not want to provide an equivalent of these functions on Windows) or whether it's an oversight.

Thanks!

[esperanto]: https://github.com/dinosaure/esperanto
[pth]: https://www.gnu.org/software/pth/pth-manual.html

**Comment by jart** [comment]
I would have thought they'd use `longjmp` and `setjmp` for fibers because `getcontext` and `setcontext` are very heavyweight data structures and I don't think libucontext is using them correctly, because they're only filling in the general registers. Musl also doesn't support this. However I don't see why we can't try adding `getcontext` and `setcontext` for this purpose. Please let me know if it works for you. Just keep in mind it's not something I recommend doing and the interface may change in the future to slow down should the need arise for obtaining the other machine bits like flags, x87, and xmm.

**Comment by jart** [comment]
I've added those two functions. If the other ones like `makecontext` are needed then contributions are welcome. Send us a pull request and see the CONTRIBUTING.md file. Thanks!

**Comment by jart** [comment]
As of today, Cosmo now has a complete implementation of setcontext(), getcontext(), swapcontext(), and makecontext() that'll work on all our supported OSes and architectures, including Windows. Enjoy! 197aa0d4652d618fd8a11c8445fc3df9bd5816bd
