### ISSUE TITLE
setlocale errors

### ISSUE THREAD

**Issue by nicholatian** [jart/cosmopolitan#43]
```
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

I get this while building cosmopolitan on my Arch Linux laptop. Any idea what could be causing that message to pop up? It doesn’t seem to impede building, but it sure is annoying as it gets echoed for *every single recipe target* that needs updating.

**Comment by jart** [comment]
This should be safe to ignore. Cosmopolitan is already C.UTF-8. I can add an implementation of that function to avoid such warnings in the f uture.

**Comment by nicholatian** [comment]
Epic. Thanks a bunch for committing to fixing it!

**Comment by jart** [comment]
Fixed and new amalgamation now pushed to https://justine.lol/cosmopolitan/download.html PTAL?

**Comment by nicholatian** [comment]
Pending Testing And Luck? Yes. If that’s what that stands for.

**Comment by jart** [comment]
PTAL = Please Take A Look

**Comment by nicholatian** [comment]
Hmm, no, it doesn’t seem to help.

I’m not sure if I made it clear enough, but I think this is happening somewhere in the build system, not in the library provisions themselves! Every target complains of this error, and `/bin/sh` is the one doing the complaining. Though I don’t know how much dogfooding you are doing with that, it could be Cosmopolitan itself for all I know.

This is how it looks in a terminal:
![Terminator](https://cdn2.arqadium.com/f/133de7c23a97406e8c2e52539d310983/unknown.png)

**Comment by jart** [comment]
Oh it seems I misunderstood your request. I assumed earlier this was being triggered by a `./configure && make && make install` workflow where Cosmopolitan was being used as the libc. Now I see the issue must be the following line:

https://github.com/jart/cosmopolitan/blob/02b4a5c824cdb56b7335ecd37e44ef0ce3dd1077/build/definitions.mk#L46

I'm going to push a commit changing that to `C` since that's what the POSIX documentation specifies. The purpose of that line is basically to ensure that any collation magic glibc may or may not have, won't impact the sorting order used by tools like GNU ld which rely on deterministic ordering, for hopefully reproducible builds.
