### ISSUE TITLE
Getting started script doesn't work well

### ISSUE THREAD

**Issue by die00** [jart/cosmopolitan#44]
Hi, the provided script in the Getting Started section doesn't work well in all shells, also the name of the downloaded file is different from the one to unzip. I fixed this doing the following:

- Change filename in the `unzip` command: `unzip cosmopolitan-amalgamation-0.2.zip`
- In zsh `echo` prints
```
main() { printf("hello world
"); }
```
which is invalid. I added the `-E` flag to ignore backslash scapes.

**Comment by jart** [comment]
Thank you for bringing this to my attention. I try to always use printf in shell scripts rather than echo. I thought I was cargo culting but apparently this is the reason why. Apropos the Z-shell I recently just upstreamed a change that'll enable your actually portable executables to launch without needing extra syntax: https://github.com/zsh-users/zsh/commit/326d9c203b3980c0f841bc62b06e37134c6e51ea
