### ISSUE TITLE
An inet_addr functionality request! :) 

### ISSUE THREAD

**Issue by PerfectProductions** [jart/cosmopolitan#47]
Hi Justine! Thank you! The new update works fantastically on linux running system("functions"). I've noted this works on Windows10 aswell. Awesome stuff!

This feels like it's not an issue, but I would love to see some inet_addr action in cosmopolitan, potentially?
Also, I have noted that the binary needs to be deleted and rebuilt each time in order to run on Windows 10.

However, this is an Official feature request To potentially add inet_addr to cosmo's features? ... 

Can this be done easily? 

let's hope so! :)

**Comment by jart** [comment]
That's great to hear!

Sure I can add inet_addr for you. I've been using `sscanf(str, "%hhu.%hhu.%hhu.%hhu", &ip4[0], &ip4[1], &ip4[2], &ip4[3])` which works nearly the same. However we should have `inet_addr()` too since it's specified by POSIX. I want Cosmopolitan to have as many compatibility functions as possible since static linking means there's no negative tradeoff to doing so.

**Comment by jart** [comment]
All fixed and I've pushed new amalgamated binaries to the website for you too: https://justine.lol/cosmopolitan/download.html Enjoy!
