### ISSUE TITLE
Getting started with cosmopolitan?

### ISSUE THREAD

**Issue by ananthb** [jart/cosmopolitan#487]
What's a good way to get started with a brand new app using cosmopolitan libc? I'm looking for ideas on how to structure the code and how to build it. I have a simple Makefile that directly compiles against the pre-compiled object file and the cosmopolitan header, but I'm not sure how to pull in zlib and other third_party libraries.

**Comment by jart** [comment]
The best way to use Cosmopolitan is by creating your own folder in this monorepo, because it makes you a first class citizen and lets you access packages (e.g. third_party) which aren't in the release amalgamation. The tutorial for getting started is here:

- https://github.com/jart/cosmopolitan/tree/master/examples/package

That folder is intended to be a template that you can copy for your own project folder. You just change the names and make sure it's listed in `Makefile`. You would then edit the list in `EXAMPLES_PACKAGE_DIRECTDEP` to add entries like `THIRD_PARTY_ZLIB`. That will ensure the `o/$(MODE)/third_party/zlib/zlib.a` gets linked into your program.

The best place to get support for Cosmopolitan style development is on our Redbean Discord. https://discord.gg/mw3j3sa2 You're invited and encouraged to join. We'll help you with everything.

**Comment by shmup** [comment]
Didn't know about that example! Nice nice.

**Comment by ananthb** [comment]
Excellent thanks. I'll check it out. See y'all on the discord!

**Comment by ananthb** [comment]
@jart the discord invite has expired apparently.

**Comment by jart** [comment]
https://discord.gg/sN53mQMt

**Comment by shmup** [comment]
To build that example package, you'd simply do a: `make o//examples/package/program.com`

**Comment by jart** [comment]
Correct. However that's to build the binary. The convention for building packages would be:

```
make o//examples/package
```

That's because at the end of every `.mk` file we have a phony target for the directory:

```make
.PHONY: o/$(MODE)/examples/package
o/$(MODE)/examples/package:				\
		o/$(MODE)/examples/package/lib		\
		$(EXAMPLES_PACKAGE_BINS)
```

This is consistent across the whole repository and it's recursive too. For example, if you wanted to build all the LIBC packages:

```
make -j8 o//libc
```
