### ISSUE TITLE
Tunable / (Per-platform) Stack Sizes

### ISSUE THREAD

**Issue by paulreimer** [jart/cosmopolitan#49]
(Forgive me if what I describe here is not a sensible thing to do:)

As a bare-metal user, I would like to set stack sizes to the size of my machine (I know exactly how big they are and I want to take it all), but that's sort of dynamic for each of my projects, and for bare-metal in general.

It would be a bonus if I could also (separately) tune my Linux stack size to something my poor dev machine can actually do, since it is in an environment where I could limit the test data I throw at it.

**Comment by paulreimer** [comment]
(I don't plan to distribute these binaries or consider anything other than Linux / bare-metal, personally)

**Comment by jart** [comment]
What you propose was a sensible thing to do, until about seven minutes ago.

I'm proud to announce that Cosmopolitan now has malloc() support on metal. See https://github.com/jart/cosmopolitan/commit/edd9297ebaf3d920f87a609ab0dc5ac64707bfc3 where I've updated the APE bootolader so that it reads the ELF program headers and maps whatever they define into memory. We use the PT_GNU_STACK program header to define the fixed address and size of the stack consistently for all operating systems. (Although officially speaking the only thing PT_GNU_STACK has historically done is it tells the Linux kernel to make mprotect actually protect memory rather than its default behavior of doing nothing and returning zero lool).

Is this recent change sufficient to meet your needs? I've got metal into a pretty good state right now. The next change is likely going to be interrupt handling, since right now all faults are triple faults without backtraces and life is going to be so much easier when that's no longer the case.

**Comment by paulreimer** [comment]
Thank you! This is awesome. It sounds like `malloc` Just Works, and I can get my ridiculous 32GB stacks from (slightly abusing?) the `PT_GNU_STACK` program header (I haven't tried this yet).

**Comment by jart** [comment]
You can do both! Stacks can be huge and dynamic memory should just work too. The x86_64 architecture basically requires us to have a dynamic virtual memory manager in order to be able to run 64-bit instructions. I've managed to make the cost of having that no more than 12kb. But obviously the footprint will grow as you start linking functions like malloc().

I'm going to close this out since we've got a centralized tuning knob for stack size across all platforms now. Let me know if you'd like a way to make configuration easier. Possibly by having an optional macro that can be defined.
