### ISSUE TITLE
Questions about security and usage.

### ISSUE THREAD

**Issue by dlannan-fmad** [jart/cosmopolitan#5]
This is a very interesting project and has piqued my curiosity. I have a few questions about it.
1. Security: If I understand correctly, there has been some elements of gcc executable security removed? And currently the source code is added to the runtime which seems a little insecure as well. I guess file and process permissions are still maintained?
2. It is mentioned that sockets can be used cross platform (network), but Im not sure how this could possibly work. Can you give me an explanation as to how winsock and sockets could work within a single exe binary.
3. Will libraries like pthreads will be problematic as well?
4. I know this is primarily pure C which is great (I work in mainly C) so the idea of cross platform building is not unfamiliar. What is the advantage of this over using something like Luajit or another bytecode based language and transport the bytecode?

Thanks for sharing the project, quite fascinating.

**Comment by dlannan-fmad** [comment]
Sorry. Im stupid. Quite clearly, some of these are dependent libraries, and so this would be an issue in any case (pthreads for example) and winsock is probably a similar issue,  
Will try out a few tests - there is mention of bare metal boot capability? Im assuming youd need a bootloader or something built into the file? Very cool work.

**Comment by dlannan-fmad** [comment]
hello.com on Debian 10 works fine, as does the ascii mpg player. I tried hello.com on a Win64 i7 Laptop and it didnt run.
Error reported: 
> "hello.com is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."

**Comment by jart** [comment]
Security is enhanced. Could you clarify why you came to a different conclusion? Perhaps I can help address your concerns. 

Berkeley and Winsock work fine in a single file. For example, the wrapper functions recv() asks the question "am I running on Windows?" If so, it delegates to WsaRecv() rather than issuing a SYSCALL to the UNIX binary interface.

Threading has no consensus amongst system interfaces. Cosmopolitan only caters to generally accepted practices rather than the controversial ones. Please note you can have all the fibers you want w/ longjmp() since that doesn't require any system call support.

Languages like Lua are awesome if you love 'em. Go with what makes you happiest! Here we focus on C / C++ / FORTRAN / JS.
