### ISSUE TITLE
Cosmopolitan C Library / GCC Toolchains

### ISSUE THREAD

**Issue by firasuke** [jart/cosmopolitan#50]
As a Linux distribution developer, how ready is cosmopolitan libc for constructing cross/native GCC toolchains that target `x86-64`, and what range of software is supported?

Thanks for the wonderful effort, and keep up the great work!

**Comment by jart** [comment]
I'm reasonably certain that Cosmopolitan implements all the libc functionality that GCC requires. However it isn't something I've tried to do, since compiling GCC from source is exceedingly difficult even if you're using a conventional C library like glibc.

Check out https://github.com/jart/cosmopolitan/tree/master/third_party/chibicc where we have a C11 compiler and integrated assembler that's able to be built as an Actually Portable Executable. All it needs is a linker. Then we'll have a toolchain in a single 200kb file that runs everywhere. The generated code won't go as fast as what GCC and Clang are able to produce. But I think there's still use cases for the convenience and embeddability such a toolchain would offer. What do you think?

**Comment by firasuke** [comment]
Technically speaking, portability won't be an issue here since I'm only targetting Linux.

I also noticed that cosmopolitan libc has arguably faster `memcpy` and (possibly) `strcpy` implementations, and I was wondering how would the lack of optimization when using a compiler like `chibicc` affect the overall performance of produced binaries (I still think `chibicc` is a great project, but only for its educational value...).

From the way I see it, here are the current shortcomings regarding bootstrapping Linux systems:

- No support for shared linking
- No support for different CPU architectures (only `x86-64`)
- Poor optimisations relating to the usage of compilers other than GCC/LLVM
- No support for a wide range of software

I understand that the points above may be the result of the direction cosmopolitan is going in (pure portability, which actually isn't all that needed when bootstrapping Linux systems) but it would still be impressive to see how far we can get.

The only thing that bothers me currently is why bother and optimize your libc (`memcpy` and `strcpy`) if you're going to rely on compilers like `chibicc` that optimixe relatively worse (or even don't optimize at all).

Again thanks for the huge amount of time and effort you put into this.

**Comment by jart** [comment]
What Cosmopolitan does, it does really well. I understand that it's not possible to please everyone in terms of features. Thanks for sharing your concerns!

**Comment by firasuke** [comment]
Good luck with cosmopolitan!
