### ISSUE TITLE
Multiple redbean sites on single server

### ISSUE THREAD

**Issue by stephenbenedict** [jart/cosmopolitan#509]
I’m not sure if this question is specific to redbean (it may be a server operations question, in which case I will take it to Stack Overflow etc.), but is it possible to run multiple redbean sites on a single server? For example, if you have two different subdomains which each point to separate redbean sites. With Apache, you would accomplish this with virtual hosts, but I’m not sure how this could be done with redbean since it is a web server in of itself.

**Comment by jart** [comment]
With redbean all you have to do is create a folder if you want virtual hosting. Let's say you have a domain name called www.foo.example. Redbean will look for assets in the following order:

```
(srvr) RoutePath("/www.foo.example/")
(srvr) RoutePath("/foo.example/")
(srvr) RoutePath("/index.lua")
(srvr) RoutePath("/index.html")
```

So you basically would just create a folder named `foo.example/` and put your virtually hosted assets there. That way you only need one server.

If you genuinely need to host multiple instances, then redbean can do reverse proxying to other redbean instances using the Lua `Fetch()` API.

Thanks for asking! Enjoy redbean!

**Comment by stephenbenedict** [comment]
Thank you for your help!

**Comment by stephenbenedict** [comment]
@jart Sorry, I realized I need to ask one more question: In the event that I need to host genuine multiple instances, would I run each redbean instance on a different port?

Basically, I want to be able to set up individual redbean instances for some clients, with each getting their own subdomain on a domain I own to point to their app, and hosted on a single server.

**Comment by pkulchenko** [comment]
You do have a couple of options. You can still serve all of the apps on different subdomains from one instance by looking at the Host headers and applying whatever logic you need (maybe loading domain specific files from different modules or DB. You can also run different instances on each subdomain and proxying requests through an instance of nginx or redbean. I do the latter in the project I'm working on: (1) responding to all the subdomains from one instance of redbean and (2) proxying some of the requests to dynamically launched instances of redbean serving custom apps on various subdomains.

**Comment by stephenbenedict** [comment]
@pkulchenko Thanks very much for the advice. For this project, I need different instances of redbean for each subdomain so I will try the 2nd approach. Would you be able to share an example of redbean as a proxy as you are using it?

**Comment by pkulchenko** [comment]
The sequence is quite simple:
1. keep track of domain-to-ip mapping in a SQLite db
2. for each new request get and parse its Host name
3. get the IP address from the DB based on the parsed host name
4. send a request to that IP (mapping the request URL) using `Fetch` function
5. return back results of Fetch setting status, headers, and body of the response (make sure to skip headers that Redbean itself controls, otherwise those SetHeader command may return a run-time error). Fetch may also return an error if it can't finish the request.

This is almost the exact logic I use with a small tweak that in my case most of these steps are dynamic (so I can start the app on a different port) and update the mapping.

**Comment by stephenbenedict** [comment]
Thank you! That is very helpful. I will try that out.
