### ISSUE TITLE
make unveiling: Output path specifity

### ISSUE THREAD

**Issue by chrysn** [jart/cosmopolitan#528]
The rule to `Unveil (dir, "rwc");` of make's `job.c:791` is very broad, and does not capture two common errors of writing Makefiles (or misbehaviors of the program):
* depending on undeclared input files, and
* writing undeclared output files.

Would it be possible to sharpen the unveil into a more narrow rule that allows only the creation of the specifically declared output file(s)?

From my rough and nascent understanding of the OpenBSD unveil semantics, this might not be possible easily (for unveiling is attached to files and not file names, and the output file often doesn't exist yet when the rules are run). Landlock, being based on file descriptors, appears to have similar limitations. I can envision workarounds that work in some cases (like, open the input and output files before exec'ing, and replace `$<` / `$@` / `$^` with the relevant `/proc/self/fd/${N}` names), but there's no shortage of ways in which this could go wrong, and anyway it'd be way exceeding what the locked Make now does.

If this can not be tightnened, it might be worth mentioning this limitation in the caveats. A suggestion there might be for authors to write Makefiles in such a way that output is only ever produced in dedicated output directories.

**Comment by jart** [comment]
You're right the approach I chose is suboptimal in cases where the user is putting source and output files in the same directory. That's something I failed to consider, since I always put output artifacts in `project/o/`.

Now that I think about it, there's an approach we could use that might work. Landlock will fail to unveil() an output file if it doesn't exist yet. What we could do is touch the file, and then set its last modified timestamp to 1970. Then, if the build command succeeds, it should roll the timestamp forward.

I'll report back as soon as I figure out if it works!

**Comment by chrysn** [comment]
Thanks for taking this up!

With touch-and-unveil-file there can be corner cases when rules or
programs remove the file before creating it, but in that case the user
can still manually unveil the whole directory. (Such cases appear in
rules if the program by default won't override, or if it would try to do
something incremental on the file -- but in the large scheme of things I
hope these are rare).

**Comment by jart** [comment]
And thank you for helping me!

I'm still fiddling with Landlock to solve the output directory problem. Also talking to people offline. I'll keep this issue updated.

Some good news on a slightly related front, is today we managed to make our [pledge.com](https://justine.lol/pledge/) sandboxing much stronger. Thanks to a suggestion on Lobsters we're using LD_PRELOAD on glibc distros to rollback permissions like `exec` and `prot_exec` which are needed to launch the executable. https://github.com/jart/cosmopolitan/commit/6b3d257588afed39837ac98d049b9947ff5aba3e We also have friendly error logging. This matters, since I can imagine in some cases pledge.com can work hand-in-glove as a subcommand wrapper invoked by Make, because it's able to offer some additional layers of security like blocking Internet access.

**Comment by jart** [comment]
Landlock Make now only unveils the target file (rather than the output directory). You've now got a much stronger sandbox. However there's some caveats you need to know. 

1. Landlock can't unveil files that don't exist. So make will touch the output file with a 1970 timestamp before launching your command.
2. Your command must not delete the output file. Some programs like GNU LD like to unlink() the `-o OUTPUT` before creating it. Doing that changes the inode. So Landlock will raise `EACCES`. You may need to write wrappers for your tools so they overwrite the file instead. For example, calling `open(output, O_CREAT | O_TRUNC | O_WRONLY)` works fine and doesn't change the inode.
3. You'll need to make more liberal use of the `o/tmp` or `/tmp` folders. If you read our change you can see there's a bunch of code I've updated where we're now doing that.

Enjoy!

**Comment by chrysn** [comment]
Awesome, gotta try that out later.

By the way, the comment on /tmp inspired https://github.com/jart/cosmopolitan/issues/530.

**Comment by jart** [comment]
Landlock Make v1.0 available on https://justine.lol/make/

@chrysn I'll take a look into the /tmp issue now. Thanks!
