### ISSUE TITLE
immintrin.h: No such file or directory

### ISSUE THREAD

**Issue by thecodrr** [jart/cosmopolitan#551]
I am trying to use cosmopolitan with Nim and failing here. I have some code that uses SIMD instructions but compilation fails with those. Is there some flag I am missing?

Here are the flags currently being passed:

```nim
-static -nostdlib -nostdinc -fno-pie -no-pie -mno-red-zone 
``` 
Normally including `immintrin.h` just works with gcc & clang.

**Comment by thecodrr** [comment]
Okay, I manually included the required headers and it worked.

**Comment by jart** [comment]
We have those headers, but we don't include them in releases currently.

- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/emmintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/wmmintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/xmmintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/shaintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/avx2intrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/smmintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/avxintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/tmmintrin.internal.h
- https://github.com/jart/cosmopolitan/tree/master/libc/intrin/pmmintrin.internal.h

We could probably move them into `libc/isystem/`. I'm not sure they're something I feel comfortable recommending, since it's a brittle API that very thinly wraps the builtins provided by GCC and Clang, which differ in strange ways. I personally prefer using the inline asm() keyword (see https://justine.lol/dox/rmsiface.txt) or the GCC intrinsics names directly.
