### ISSUE TITLE
warning: allocated section `.tdata' not in segment

### ISSUE THREAD

**Issue by andy5995** [jart/cosmopolitan#565]
* Manjaro 21.3.6
* gcc (GCC) 12.1.1

I get these warning when  using the command line shown on the README:

```
/usr/bin/ld.bfd: hello.com.dbg: warning: allocated section `.tdata' not in segment
/usr/bin/ld.bfd: warning: .note.gnu.build-id section discarded, --build-id ignored
```
Just thought I'd report it in case it's something you'd like to address. No problem for me. ;)

```
gcc -g -Os -static -nostdlib -nostdinc -fno-pie -no-pie -mno-red-zone \
  -fno-omit-frame-pointer -pg -mnop-mcount -mno-tls-direct-seg-refs \
  -o hello.com.dbg hello.c -fuse-ld=bfd -Wl,-T,ape.lds -Wl,--gc-sections \
  -include cosmopolitan.h crt.o ape-no-modify-self.o cosmopolitan.a
```

/cc @jammyjamjamman

**Comment by jart** [comment]
I wish I could address it. It's been happening ever since we introduced `_Thread_local` support. I've tried to make it go away multiple times but haven't been able to figure out what's causing it. It appears to be harmless.

If anyone who reads this is a linker script expert who can help us solve this, please see `ape/ape.lds`.

**Comment by tkchia** [comment]
Hello @jart, hello @andy5995,

I had lately been messing around with TLS support [for a separate project of mine](https://gitlab.com/tkchia/solidate/-/blob/99ad0449d64a155f88e70fcdf3029fcb0f199fe7/solidate.ld).  I found that I had to do a few things:

  * The `.tdata` and `.tbss` sections are _not_ meant to be the actual TLS area for the first thread, but rather as _initializers_ to be used to prime the TLS contents of each thread, including the first thread.  So the `.tdata` contents need to be copied out to some other place at run time.  (Think of `.tdata` as an area of ROM, which you copy out to RAM, in order to initialize the RAM.)
  * The `.tdata` section should be assigned to _two_ program segments: a `PT_LOAD` segment, and a `PT_TLS` segment.  (Since `.tdata` 's contents are read-only, it can go into a read-only `PT_LOAD` segment.)
  * The `.tbss` section only needs to be assigned to a `PT_TLS` segment.

One thing to note: the `.tbss` output section definition will _not_ advance the location counter within the script.  That is, the section that appears after `.tbss` will be allocated at the same address (subject to alignment) as `.tbss` itself.  (!)

I also came across a [write-up by Ulrich Drepper](https://lrita.github.io/images/posts/cplusplus/ELF_Handling_For_Thread-Local_Storage.pdf) on the intended manner of use for the `.tdata` and `.tbss` sections.

Thank you!

**Comment by tkchia** [comment]
Hello @jart, hello @andy5995,

It seems to me that the Cosmopolitan code already copies the contents of `.tdata` out to a separate memory area, so most probably a few simple tweaks to the `ape/ape.lds` linker script should be able to solve the issue.  Let me see if I can work out something.

Thank you!
