### ISSUE TITLE
printf doubles with %lf gives nan

### ISSUE THREAD

**Issue by ahgamut** [jart/cosmopolitan#58]
Hi, I tried out a bunch of portable executables in Linux and Windows, and they all worked perfectly :).

However, when I compiled and ran the below code:

```c
int main() {
    double x = 0.25;
    double y = sin(x);
    printf("sin(%f) = %f\n", x, y);
    printf("sin(%lf) = %lf\n", x, y);
    return 0;
}
```

The output is:

```
sin(0.250000) = 0.247404
sin(0.000000) = nan
```

When I compile using `gcc -lm` the output is same for both.
Do I have to add a compilation flag to print doubles via `%lf`?

**Comment by alisonatwork** [comment]
I believe this might be a bug. I haven't had time to compile the project yet, but this might fix it.

```patch
--- a/libc/fmt/palandprintf.c
+++ b/libc/fmt/palandprintf.c
@@ -215,6 +215,10 @@ hidden int palandprintf(void *fn, void *arg, const char *format, va_list va) {
         signbit = sizeof(intmax_t) * 8 - 1;
         break;
       case 'l':
+        if (format[1] == 'f' || format[1] == 'F') {
+          format++;
+          break;
+        }
         if (format[1] == 'l') format++;
         /* fallthrough */
       case 't': /* ptrdiff_t */
```

See: https://en.cppreference.com/w/c/io/fprintf

`%lf` and `%lF` (plus a couple other float formats) should resolve to `double`, not `long double`.

**Comment by jart** [comment]
Thank you not only for bringing this to my attention, but for taking the time to send a PR too.

One thing worth mentioning is that the best way to format floats is Cosmopolitan is by doing the following:

```c
printf("%s\n", gc(xdtoa(3.14)));
```

That's the wrapper we define for generalized dtoa which in my opinion formats much more readable numbers than the standard for the printf interface would otherwise enable us to do. 

I should also mention that Cosmopolitan's floating point printf() is somewhat underdeveloped for that reason. The main thing it's lacking right now is exponents. It also isn't femtoscale accurate like the generalized dtoa functions are.
