### ISSUE TITLE
Crash when running any ape on Windows 7

### ISSUE THREAD

**Issue by G4Vi** [jart/cosmopolitan#617]
None of the test executables appear to run on Windows 7 now.

Used `make -j4 MODE= o//test/libc/calls` to build.

```cmd
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\Downloads>sigpending_test.com
crash 0xc0000005 rip 00406293

C:\Downloads>printargs_test.com
crash 0xc0000005 rip 004089a3

C:\Downloads>sigpending_test.com --strace
crash 0xc0000005 rip 00406293

C:\Downloads>printargs_test.com --strace
crash 0xc0000005 rip 004089a3
```

`git bisect` reveals:
```bash
b69f3d2488dbaf9dcc541e699f5b7c09fbf046e0 is the first bad commit
```
https://github.com/jart/cosmopolitan/commit/b69f3d2488dbaf9dcc541e699f5b7c09fbf046e0

**Comment by jart** [comment]
I don't think I can support it anymore. My Windows 7 VM croaked a few months ago. It wasn't very pleasant while it was working either, because even though I paid for a license, once Win7 hit EOL, Microsoft reprogramed the VM to show me all these invasive warnings about piracy. I can't support what I can't test. Windows 7 has issues like not supporting a 64-bit address space, and needing exponential backoff when talking to many APIs. If there was an easy way to run Windows 7 and SSH into it without being treated like a criminal, then I'd be happy to support it. Otherwise we might want to bump the support vector up to a more recent version.

**Comment by jart** [comment]
For reference, here's when I removed win7 from the test fleet. https://github.com/jart/cosmopolitan/commit/13c1c45075cb2a12e0624d392da9382cca040e4b

**Comment by pkulchenko** [comment]
FWIW, it still works for me on Windows 8.

**Comment by jart** [comment]
Thank you for reporting in @pkulchenko ! That's the one I was really worried about.

**Comment by pkulchenko** [comment]
I would have tested on my win 7 machine, but it's unfortunately running 32bit version ;(

**Comment by jart** [comment]
@G4Vi I've officially sunset our Windows 7 support. While it's gone, it's not forgotten. Cosmopolitan v2.0 should still work. If you wish it, we can create a `v2` branch. You can then send us PRs backporting any functionality you need, and I'll issue releases for them. The same goes for anyone else reading. I hope this will be a satisfactory outcome to this issue. Thanks for the report!
