### ISSUE TITLE
Linux ARM support

### ISSUE THREAD

**Issue by ccpster** [jart/cosmopolitan#633]
Hi,

I just learn this project from Hacker News. I found it very interesting and I would like to use it. My primary platform is RaspberryPi 4. So I tried follow Readme.md Source build instruction. But it does not work for me. Many qemu core dump messages.

So I am thinking porting it myself. I wonder if there already a porting effort going? I world like to joint. If not can you give me some pointer for how to getting start?  I think I need to learn ARM assembly programming. but is there anything else I should know to begin?

Thanks.

Ping.

**Comment by jart** [comment]
We'd love to support Linux on ARM. The way we intend to do it so far is by embedding Blinkenlights in the binaries, as described by the APE blog post. The best way you can help out and get involved right now, is by helping us to improve Blinkenlights. For example, there's a lot of Linux system calls that it still needs to support, in order to provide a level of emulation that'll work for most programs. If you have an x86-64 machine to do your development in the meantime (since we're still a ways off from configuring our build system to compile blinkenlights into an ARM executable) then you can get started as follows:

```
make -j8 m=fastbuild o/fastbuild/tool/build o/fastbuild/examples/hello.com
o/fastbuild/tool/build/tinyemu.com o/fastbuild/examples/hello.com
o/fastbuild/tool/build/blinkenlights.com -t o/fastbuild/examples/hello.com
```

**Comment by jart** [comment]
Rolling this issue into our grand Linux+ARM issue. See also #612, #354, #139, #73, #55, #642

**Comment by paulwratt** [comment]
regarding Qemu on Aarch64, you mention 48-bit address space in a previous Issue, and I noticed the same comment resolved the major problems with running on Windows 7/8/Vista

is there a possible solution in there somewhere? (besides getting blinkenlights running)

**Comment by jart** [comment]
We tolerated Windows Vista's limited address space in the past (back when I actually had access to old Windows instances) because it's easy to detect the Windows version and it's all exceedingly well documented. I don't know how to detect that I'm running inside a qemu-user instance on a Raspberry Pi, other than trapping SIGSEGV or poking around with mmap() failures, which would be too heavyweight to impose on all APE binaries across platforms. Qemu RasPi isn't a very big fish in terms of platforms and it should be emulating a normal environment.

**Comment by Jan69** [comment]
sux that blinkenlights itself being an APE means it's basically of no help at the moment, neither tinyemu nor blinkenlights run properly, even when assimilated...

**Comment by jart** [comment]
Yes but that can and will change. It's what we intend. That's why I recommend contributors consider helping us improve it. Any time invested in Blinkenlights today will pay dividends as its platform support expands. It's been designed from the start to be ready for day when it comes.

**Comment by jart** [comment]
Download the latest redbean releases here: https://cosmo.zip/pub/cosmos/bin/ We'll do a release on redbean.dev soon!

**Comment by jart** [comment]
redbean runs natively now on both amd64 and arm64. We do it by embedding two builds in the same binary. Read more about our technique here: https://justine.lol/cosmo3/

**Comment by xet7** [comment]
@ccpster @jart 

Redbean works on Linux arm64. So maybe close this issue?

**Comment by jart** [comment]
Mission accomplished. https://justine.lol/cosmo3/
