### ISSUE TITLE
Compile Godot Engine headless mode in APE format.

### ISSUE THREAD

**Issue by fire** [jart/cosmopolitan#720]
I work on Godot Engine and it came to me in a conversation that it should be possible to compile Godot Engine 4.0 headless as an APE format.

- [x] Review docs for how to compile an hello world executable
- [x] Patch Godot Engine scons build system on the linuxbsd platform
- [ ] Test iteration loop
- [ ] Execute on Windows
- [ ] Execute on Linux
- [ ] Execute on the Mac
- [ ] Execute on WASM

WIP: https://github.com/V-Sekai/godot/tree/actual-portable-executable

**Comment by jart** [comment]
I'm excited that you're trying APE. I can also see that Godot Engine 4.0 is a 2d/3d game engine. Our software is currently only intended to support command line applications. GUI apps need to depend on a lot of dynamic shared object libraries, and APE binaries need to be static executables. I'm going to close this issue since it isn't a bug or feature request.

**Comment by fire** [comment]
Godot Engine can be compiled as a command line server application as you specify.
