### ISSUE TITLE
WASI?

### ISSUE THREAD

**Issue by vitiral** [jart/cosmopolitan#8]
I've spent about an hour going down the rabbit hole of this source repository. I'm horrified, baffled, amazed and enthused all at once. If this project even half works it is fundamentally a work of art. I feel like what it does better than anything is lay out in gory details the mind bending complexity that our software and platforms have put on us engineers in order to get _anything_ to work. Excellent work.

Related to that, I the feeling I get from this project is a wakeup call for more portable binaries. Have you heard of [wasi](https://wasi.dev/)? I feel it aligns with all of the goals of this project but is far simpler. I mention it here because I didn't see a reference to it in your docs, which I found confusing.

Obviously WASI can't instantly run on ANY system with zero dependencies -- what you've created is something I couldn't have dreamed was possible.

**Comment by jart** [comment]
Thank you! I also recommend reading the [Actually Portable Executable](https://justine.storage.googleapis.com/ape.html) blog post if you haven't already.

Cosmopolitan absolutely works and supports the half of things we need (e.g. processes and fibers) but that might not include half the things you want (e.g. threads since it can't be done across operating systems unless you depend on their local tools).

I had not heard of WASI until now. Their [script for running unix binaries in the browser](https://wasi.dev/polyfill/polyfill.js) looks super promising. I want that. 

As for wasmtime it looks like another attempt at enriching native software with an App Store restrictions model. I wouldn't sign up to run my apps in a 32-bit JVM unless platforms made it a hard requirement, and even then I would consider taking my work elsewhere. LLVM also JVM for their IR byte code.. Google has a similar tool called gVisor does restrictions via ptrace without the need to recompile binaries similar to AppArmor and SELinux once did in the past.

Cosmopolitan isn't a layering technology that sits between you and the system. It's just a really good C library that uses on a binary isomorphism I discovered that's common to Mac, Windows, FreeBSD, OpenBSD, and all Linux distros (including old ones). It doesn't have dependencies. No runtimes, dependencies, or virtual machine are required unless the architecture is non-x86. If you're OK with distributing binaries that run faster on x86 than any alternative, with emulation for everything else, then Cosmo ought to suit you!

**Comment by vitiral** [comment]
By "half works" I mean that I will be solidly impressed if software compiled this way (with the restrictions you say) half works at all... on half the systems you say it supports. Seriously, several of these files can act as a _working cheat-sheet_ of operating system API ~internals~ bloody guts. I'm super enthused but also have trouble trusting a source repository 750,000 lines long written/modified by a single person -- which is why I say horrified and amazed. The revelation you had that all these platforms support some archane shell-injection is a minor point to being able to exploit it to this extent _by yourself_.

WASI/wasmtime isn't so much AppStore (although it shares somewhat similar goals), it's more like an ultra-lightweight docker for only WASM. You give it the exact permissions you want (which files/directories, sockets, clock, etc) and it runs in a very lightweight container that can't access anything outside. WASM's stack-machine is way simpler than JVM too, just i32/i64 and basic assembly instructions but lacking arbitrary jumps (`tables` are provided for indirection), which allows for static memory out of bounds checking at compile time (idea being the host compiles the code so can ensure security). [Here](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/) is an entertaining overview if you're interested. My personal desire is to write an OS (bootstrapped forth with only ~1000 lines of assembly, see CollapseOS.org for my inspiration, Civboot.org for what I'm trying to build) and write a WASM-compiler + WASI-runtime that runs directly in the kernel to provide the security. "User" processes are then simply a "shell" running in a WASI container that can spawn other WASI containers with a subset of their privileges.

To me, it's fine that Cosmopolitan doesn't provide containerization. Neither do binaries and that's not a design goal. You want a compile-once run-anywhere for the world of programs compiled with GCC. In fact, if you wanted to distribute a WASI runtime you might do so using Cosmopolitan... You could even distribute a WASI program by bundling a downloaded-not-trusted WASI program with your cosmpolitan-wasi-runtime (in a zip maybe?) and have the later run the former to get both crossplatform+security. Horray!

Super cool stuff.

**Comment by jart** [comment]
You're in luck. I just built [a static web server today called redbean](https://justine.storage.googleapis.com/redbean/index.html), but it hasn't been published this yet. HTTP serving is a well understood problem. So it should be super easy to identify any issues and verify my claims. If you do that, we can prove that Cosmopolitan is indeed a work of art.

As for trust, you can trust that I've curated a lot of interesting ideas from places like Bell Laboratories, guys like Phil Katz, Richard Stallman, and Tim Patterson, while reviewing a lot of BSD/MIT/ISC licensed code. My personal contribution aren't what's important here. What matters is there exists a beautiful yet poorly understood consensus surrounding system interfaces, which Cosmopolitan brings into focus. That consensus was forged over the course of decades by countless unsung heroes whose contributions sadly enough tend to get swept aside by commercial interests and platform abstractions. If I can nudge the best systems engineering knowledge back into the spotlight by just a little bit, then I'd say that's a pretty decent achievement.

Security is in the eye of the beholder when it comes to container technologies. Java Applets and Macromedia Flash were successful and ASM.JS did a great job enabling Gawker to flash the microcode of AMD K8 CPUs. Browsers don't grant us the option to choose to disable WebAssembly, so I hope we got it right this time. Until then, I believe the best strategy for trusting random Internet code is monitoring. I'm noticing wasmtime makes that difficult. Doing an strace of their hello world copy a file example (which is basically just a C program that calls read() and write() nothing more) reveals so many futexes and stack switching signals flying around you'd swear it's Erlang. Cosmopolitan provides a tiny 200kb program that visualizes full x86_64 emulation if you're willing to trade away performance to see what's happening. Here's a demo of it running Antirez's Kilo: https://justine.storage.googleapis.com/tty.mp4

I support your vision. Did you see [SectorForth](https://github.com/cesarblum/sectorforth/) which got posted to HN recently? It's outstanding. Wasmtime being 20 megs is pretty good compared to Java, but SectorForth is playing the game on a whole new level, being 10x smaller than Altair BASIC while running natively on modern PCs. Stuff like that is so cool. If Cosmopolitan can be useful in any way to folks doing work like that, then I'd be super happy. For example: https://justine.storage.googleapis.com/forth.mp4

**Comment by vitiral** [comment]
Nice, redbean looks awesome. Suggestion before launch: add a link to an example site hosted with redbean -- or if that page is such a site, say so along with the commands to create it (I'm imagining it's just stuff an html file and the cosmopolitan binaries in a zip and run a command).

I'm not sure which WASM runtime you are running, but I doubt the complexity you're seeing is necessary (current wasm doesn't even have mutexes... so why futexes???). WASM itself is an ultra-simple stack machine. For Civboot I'm extremely willing to escew some performance to keep code small and simple as well as reduce the layers of complexity. 20MiB is out of the question, I'm _hoping_ CivBoot can manage to build a chip with 512k RAM... which might easily be 20-30 years in the future. So ya, when I finally write a WASM/WASI runtime it will NOT be very performant -- but it will be simple, secure and hopefully under a few thousand lines of [typeforth](https://github.com/civboot/triforth/blob/master/typeforth.md) code (the dialect I'm creating). Furthermore, I believe Civboot will probably need to create it's own stack-cpu, which should provide an almost 1:1 mapping to stack-based languages -- improving the simplicity even further.

I just started to learn assembly to build triforth, so I wouldn't trust myself to inspect an assembly dump/dbg session haha

I saw SectorForth! Super cool demonstration of what makes Forth awesome. IMO wasm compilation doesn't need to be much more complicated, but I will know more after I write a wasm->x86 compiler in Forth.

This project has actually given me an interesting idea: I could use the magic numbers and sh-injection method you've documented to allow my forth implementation to be able to run anywhere. I'm curious, do you think you can release those files/concepts on a more permissive license (i.e. MIT, UNLICENSE, CC)? I kind of doubt magic numbers and shell injection methods CAN have copyright claims made to them, but I'm no lawyer and copyright freaks me out, which is why CivBoot software is UNLICENSE throughout.

**Comment by jart** [comment]
I was running the wasmtime program described in the blog post you linked earlier. 

WebAssembly might seem simple to you, but it's all greek to me. If you understand the wasm spec well enough to code a switch statement in a single C file that decodes an octet stream, and does anything, no matter how slow, then I'd love to read it.

Cosmopolitan is super simple. All you need in order to use Cosmopolitan to create portable binaries for your project is a .a file and shell one-liner:

    gcc -O -s -static -nostdlib -nostdinc --Wl,--oformat=binary -Wl,-T,ape.lds \
        -o hello.com hello.c -include cosmopolitan.h crt.o ape.o cosmopolitan.a

The licensing shouldn't be an issue. Your employer Google is more than welcome to send me $1,000 on PayPal for a commercial license lasting one year that applies to the entire company. Google and Apple both spent hundreds of millions of dollars creating Clang and libc++ which still need glibc. All Google and Apple need to do, to complete their triforce, is pay $1k for a Cosmo license.

Lastly please note this project DOES NOT perform shell injection. Thompson-style UNIX shell scripts are not a bug.

**Comment by vitiral** [comment]
triforce and civboot are not google sponsored projects, so they probably won't fork over the cash. Maybe I will... except I just want to work on open source stuff so probably won't have a need.

Good luck with the project! I would love to see these goals work more broadly :smile:

**Comment by jart** [comment]
Reach out to OSPO. Tell them I wrote it. I've never known a manager who would refuse a small favor. If you get them to click the PayPal button, then you'll be taking care of compliance for all Googlers. Then, with Google's permission, I'd like to add their logo to a Customers section in the README.

**Comment by jart** [comment]
Marking as closed to remove from issue queue.
