### ISSUE TITLE
Is it Possible to Compile Frameworks such as the Qt framework?

### ISSUE THREAD

**Issue by thebigG** [jart/cosmopolitan#83]
Hi there,

found this project and I thought it was pretty cool! I know from reading the docs that this is meant for C, but how feasible would it be compile [Qt](https://github.com/qt/qtbase)? 

I tried and couldn't get it to work :smile:. `g++` gives me so many errors to the point that I cannot see all of them in the shell.

Again I know it might be outside the scope of the project, but is it even on the roadmap to support C++ for this kind of thing? Just curious.

Cheers!

EDIT: Most errors appeared to be related to generating templates for `std::vector`.

**Comment by Qix-** [comment]
In a broader scope, can the issue of platform-specific code be addressed? How would one go about that?

**Comment by jart** [comment]
It's possible but would be require burning tremendous amounts of resources, since there aren't really any low-hanging fruit opportunities in terms of commonalities across gui frameworks. So I would discourage spending your time working to make that happen, since such an effort is unlikely to succeed.

There are however two changes along these lines that I would potentially encourage:

1. It might be nice to support raw x11 protocol, see pointers in https://github.com/jart/cosmopolitan/issues/35#issuecomment-782692048
2. It might be nice to get Chromium to build with Cosmopolitan, which right now is blocked by #27 

See previous discussions in #1 and #35.
