### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by TechnologyClassroom** [jart/cosmopolitan#834]
What is the interaction between GCC and Cosmopolitan? It seems like Cosmopolitan should probably by copyleft like GCC, but I could be wrong.

**Comment by jart** [comment]
Cosmopolitan Libc is primarily licensed ISC and other notice licenses (e.g. MIT, BSD, etc.) which are documented on a per-file basis. Cosmopolitan Libc is not subject to any copyleft licenses.

Cosmopolitan uses GCC to compile C and C++ code. We wrote a patch for GCC called [portcosmo.patch](https://github.com/jart/cosmopolitan/blob/8dc11afcf6ad66276116211f6b1b9d9ced7c5588/third_party/gcc/portcosmo.patch) which modifies the GCC compiler so that it can support compiling code like `switch (errno) { case EINVAL: ... }`. We need that change because Cosmopolitan Libc defines constants like `EINVAL` as linkable symbols and we need to be able to use them in contexts that would otherwise require constant expressions. Our changes to GCC are [documented here](https://github.com/jart/cosmopolitan/blob/8dc11afcf6ad66276116211f6b1b9d9ced7c5588/third_party/gcc/README.cosmo) and you have the freedom to use them under your choice of the ISC or GPLv3 license.

Cosmopolitan distributes GCC binaries via our [third_party/gcc/](https://github.com/jart/cosmopolitan/tree/master/third_party/gcc) folder. We need it because we can't require users compile GCC themselves from scratch before being able to use our project. These binaries were compiled by me, to include the patch we've open sourced above. You have the freedom to recreate these binaries on your own using musl-cross-make, which we've set up in the following branch: https://github.com/ahgamut/musl-cross-make/tree/portcosmo The musl-cross-make config I used to build these binaries is documented here [third_party/gcc/config.mak](https://github.com/jart/cosmopolitan/blob/8dc11afcf6ad66276116211f6b1b9d9ced7c5588/third_party/gcc/config.mak).

Nothing in the Cosmopolitan project links GCC, which is isolated to its respective `third_party/` folder. We only use GCC and binutils as independent commands, which are run by GNU Make and our `cosmocc` shell script. 

Cosmopolitan does not use GCC runtime libraries. We use the LLVM compiler_rt instead of using libgcc. None of the libraries we use are subject to copyleft licenses.

There is some software we've written that *is* subject to copyleft licenses. For example, we've enhanced GNU Make. The sources for it are in our third_party/make/ folder. If you compile `o//third_party/make/make.com` then that will be subject to a copyleft license, because it links GPL code. You have the freedom to use our changes to GNU Make under your choice of the ISC or GPLv3 license.
