### ISSUE TITLE
Suggestion for auto detection of processor type

### ISSUE THREAD

**Issue by feeley** [jart/cosmopolitan#86]
It would be nice if the processor type could be determined at run time so that the same executable could run on different processors.  I've done processor auto-detection in the past and can suggest the following approach which can discriminate between x86-32, x86-64 and arm processors.  Perhaps this could be extended to other popular processor architectures.  The code would have to be executed as the very first thing (not as a function).

```
;; The architecture of the host system can be determined by executing
;; a carefully written piece of code which is valid on all the
;; architectures, but with a behavior which depends on the
;; architecture.

;; This particular piece of code is a function which returns an
;; integer code.  The code is -4 on ARM, 0 on X86-32 and 4 on X86-64.
;; This code assumes that the result of a function is returned in
;; register R0 on ARM, in register EAX on X86-32 and RAX on X86-64.

                    ;;       ARM              X86-32            X86-64
                    ;;
#xEB #x0A #xA0 #xE3 ;;      mov r0,#962560    jmp x86           jmp x86
#x03 #x00 #xE0 #xE3 ;;      mov r0,#-4        ...               ...
#x1E #xFF #x2F #xE1 ;;      bx  lr            ...               ...
                    ;; x86:
#x48                ;;                        dec eax           xor rax,rax
#x31 #xC0           ;;                        xor eax,eax
#x48                ;;                        dec eax           inc rax
#xFF #xC0           ;;                        inc eax
#xC1 #xE0 #x02      ;;                        shl eax,0x2       shl eax,0x2
#xC3                ;;                        ret               ret
                    ;;
                    ;;      returns -4        returns 0         returns 4
```

**Comment by jart** [comment]
That's very interesting. APE uses a similar polyglot between i8086 and x86_64 here:

https://github.com/jart/cosmopolitan/blob/3c24c12068b5dd245bd26419c6970b296a3c213f/ape/ape.S#L184-L186

It's so cool that you managed to hybridize that with ARM too! I tried to do that once, but I was quickly discouraged when `MZqFpD='` decoded as an invalid sequence. If the `qF` could be changed into a valid ARM sequence without breaking x86, then it would be possible to create flat binaries that runs on both ARM and x86.

This business might be purely academic though, since Linux and other modern systems won't run flat binaries and balk if `Elf64_Ehdr::e_machine` doesn't match. The APE shell script can patch that based on `uname -m`. But if it needs to do that then it could patch the entrypoint address too, thus obfuscating the need for the polyglot.

It'd be great if ARM encodings exist that are not only valid in x86 too but also share a similar purpose. For example, it's possible to write problems using a subset of Intel's ISA that's valid under i8086 + i386 + x86_64. Here's an lz4 decompressor that's an example of such a program: https://gist.github.com/jart/71c4035b6ea60ed3e72679783d3615b0 It's a great example of how a multi-architecture binary can be flat instead of fat. If it's possible to do something like that with ARM too, then I'd love to retool chibicc's code generator to generate such programs. https://github.com/jart/cosmopolitan/blob/master/third_party/chibicc/codegen.c

**Comment by jart** [comment]
I'm closing this out to take it out of the work queue. Thank you though for sharing a smart idea. I'd encourage you to write a blog post about this polyglot since that'd likely be of interest to the Hacker News community. If you do that, post a link here.
