### ISSUE TITLE
Implement OSX futex-equivalent (`__ulock_wait/__ulock_wake`) to futex

### ISSUE THREAD

**Issue by autumnjolitz** [jart/cosmopolitan#876]
The overview at https://shift.click/blog/futex-like-apis/ characterizes that OSX and even semi-obscure BSDs (disclosure: I use DragonFlyBSD) have futex-equivalents.

given that the futex polyfill applies a check-wait/sleep approach (ie it can be delayed after an effective futex wake), would it be an appropriate thing to consider implementing for OSX (since 10.12, Sierra, 2016) `__ulock_wait/__ulock_wake`? It’s been part of libc++ and it’s unlikely Apple would remove it despite being a private API as they would break libc++ linked apps badly and futex’es are popular enough to make such a decision to move away from such increasingly unlikely.

The blog author wrote a Rust crate to demo using it: https://github.com/thomcc/ulock-sys

My interest in this is mostly academic as I wanted a futex like that would work on OSX, DragonFly and Linux for one of my projects. 

Cosmopolitan’s polyfill, the linked blog post and various OS manual pages have been helpful at helping me understand the state of the Futex union. It’s my hopes my findings here can help improve cosmopolitan libc as well.

**Comment by jart** [comment]
Wow this is a wonderful suggestion. I've always wondered how to do this on XNU. On Apple M1 we've been using Grand Central Dispatch via the system DSOs. But we don't use DSOs on x86 XNU. Also I really want the ability to get `EINTR`. If ulock_wait/wait has that, then we might use it on both architectures.

**Comment by jart** [comment]
I managed to get all tests passing with ulock by *not* using process shared mode. We normally enable pshared mode when waiting on the "clear child tid" futex that pthread_join() waits on. However enabling pshared mode with ulock for those futexes caused `popen_test`, `fds_torture_test`, and `pthread_atfork_test` to fail for reasons that aren't clear to me yet. Yet using process private mode caused everything to pass, so I'm happy for now, since cross-process futexes has spotty support across platforms anyway.

@autumnjolitz It excites me to hear you're interested in potentially getting involved with Cosmo development. That's great to hear. We pay close attention to GitHub, but it's worth mentioning that most of the action happens on our Discord server: https://discord.gg/ct73HWDD We'd love to see you there!

Anyway I'm going to push a change closing this out. Thank you again.
