### ISSUE TITLE
-Wno-error is being ignored and -Werror is the default

### ISSUE THREAD

**Issue by feeley** [jart/cosmopolitan#91]
While compiling Gambit I'm getting the following fatal errors that can't be suppressed by adding `-Wno-error` to the gcc command line.  Any idea how to get around this (in particular the frame size limitation which I can't avoid)?  I did try `-Werror=frame-larger-than=20000` but that seems to be ignored too.

```
os_time.h:254:13: error: redundant redeclaration of '___process_times' [-Werror=redundant-decls]
  254 | extern void ___process_times
      |             ^~~~~~~~~~~~~~~~

_kernel.c: In function '___H___kernel':
_kernel.c:29406:1: error: the frame size of 17344 bytes is larger than 4096 bytes [-Werror=frame-larger-than=]
29406 | ___END_M_COD
      | ^~~~~~~~~~~~
cc1: some warnings being treated as errors
```

**Comment by jart** [comment]
That's designed to be worked around by defining `-DSTACK_FRAME_UNLIMITED`. I've designed Cosmopolitan so that a 64kb stack size with a 4kb guard page may be sufficient. We need that warning in order to guarantee that stack overflows are detected. I'm going to put that functionality behind a `-DCOSMO` define because so much open source code exists that assumes malloc is slow. Once this issue is closed you'll find a new nightly available for download at https://justine.lol/cosmopolitan/download.html
