### ISSUE TITLE
How to add libs to redbean

### ISSUE THREAD

**Issue by jperon** [jart/cosmopolitan#911]
As a perfect newbie in C world, I’d like to know whether there would be guidelines to compile and integrate libs (especially available from luarocks, but the one I’ve in mind now is [lpeg](https://www.inf.puc-rio.br/~roberto/lpeg/)) into redbean.

Many thanks for all this work!

**Comment by pkulchenko** [comment]
@jperon, you can try to compile lpeg (or another library) into redbean (look at how this is done for `lsqlite` for example) or check on the lua-only equivalents (for example, [LuLPEG](https://github.com/pygy/LuLPeg) for lpeg). Otherwise your options are limited, as there is no support for dynamic library loading.

**Comment by jart** [comment]
@pkulchenko is correct. @jperon I'd integrate it for you, but we already have two pattern matching solutions. One is the one that's built into Lua. The other is the lre.c library I wrote a while back before I understood how good Lua's built-in pattern matching API is. If you have any other suggestions for native modules you want, then leave a comment here, and I'll consider incorporating them!

**Comment by jperon** [comment]
@jart Thank you for your reply. The reason I wanted to integrate lpeg, apart the fact it’s quite "standard" in Lua world, is that [MoonScript](moonscript.org) builds upon it. But LuLPEG does the trick.
