### ISSUE TITLE
Support for OS specific random sources across multi-arch builds

### ISSUE THREAD

**Issue by jaromil** [jart/cosmopolitan#937]
Dear @jart and cosmopolitans,

First of all, since this is my first issue here: Thanks for all your great work 🙌🏽 I enjoy following you since years now.

My question as per title of issue is about compiling portable software that access random generators.

Access to random generators on different platforms changes a lot: just Linux has two (direct `/dev/urandom` and `SYS_getrandom`) and then WIN and BSD have other means (`CryptGetRandom` and `arc4random`) just to mention the most common examples.

Many code bases as for instance the excellent and portable randombytes implementation here https://github.com/dsprenkels/randombytes use pre-processor defines that refer to OS or toolchain-specific flags to switch one or the other implementation.

Is there a way to hook target-related pre-processor defines in cosmopolitan? Can we for instance compile randombytes making sure the right defines are switched on depending from targets, or perhaps adjust them so that cosmopolitan works for it?

**Comment by G4Vi** [comment]
Cosmopolitan has cross-platform `getrandom` https://github.com/jart/cosmopolitan/blob/master/libc/calls/getrandom.c . When porting software, you should configure it to use `getrandom`. When I ported Wasm Micro Runtime to cosmopolitan I had to set it to use `getrandom` instead of defaulting to `/dev/urandom` for it's `random_buf` func.

Unfortunately, I don't think there's an automated way switch the defines for cosmopolitan. If I was trying to port that library linked, I would set it to use `randombytes_linux_randombytes_getrandom` if `__COSMOPOLITAN__` is defined.

**Comment by jaromil** [comment]
Many thanks, @G4Vi. Your answer is very helpful.
