### ISSUE TITLE
Weird behaviour when using dlopen on wsl2

### ISSUE THREAD

**Issue by JoshuaWierenga** [jart/cosmopolitan#938]
I had hoped that the Linux helper would work under wsl but currently it seg faults in the asm block at the end of elf_exec. The weird thing is that I can sometimes get the example program to run fine.

I tried the major build modes and it works fine under zero and opt but cosmocc fails to update with dbg with 
`libc/dlopen/dlopen.c:283:1: error: the frame size of 4192 bytes is larger than 4096 bytes [-Werror=frame-larger-than=]`, 
other modes I have tried will build a test program but then seg fault with no additional info and as the modes with strace work fine it's been hard to get any other info.

**Comment by JoshuaWierenga** [comment]
It just occurred to me I haven't tried `MODE=` directly and for some reason it works.

client.c:
```c
#include <stdio.h>
#include <unistd.h>

int test() {
    printf("Running client: %ld\n", (long)getpid());
    return 0;
}
```

host.c:
```c
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  printf("Running host: %ld\n", (long)getpid());
  
  void *client = dlopen("./libclient.so",  RTLD_LAZY);
  if (!client){
    fprintf(stderr, "%s\n", dlerror());
    exit(1);
  }
  
  int (*client_main)(void) = dlsym(client, "test");
  if (!client_main){
    fprintf(stderr, "%s\n", dlerror());
    exit(2);
  }
  
  return client_main();
}
```
<br />

Running this works fine.
```sh
gcc -c -fpic client.c
gcc -shared -o libclient.so client.o
export MODE=
cosmocc -o host.com host.c
./host.com
```
Output:
```
Running host: ...
Running client: ...
```

But then running this after gives a seg fault.
```sh
unset MODE
cosmocc -o host.com host.c
./host.com
```
Output:
```
Running host: 1117283
zsh: segmentation fault  ./host.com
```

**Comment by JoshuaWierenga** [comment]
Turns out the rebuild is not relevant, MODE just has to be set so doing `unset MODE` and then running the working build will also give a seg fault.

**Comment by jart** [comment]
Works fine for me on Debian (glibc) and Alpine (musl). Cosmo's dlopen() support is very primitive right now, as mentioned in the release notes: https://github.com/jart/cosmopolitan/releases/tag/3.0.2 The only known issue that might be causing this is WSL's printf() function depending on TLS. I haven't decided yet how I'm going to address that. Wrapping every function dlsym() returns with a trampoline that calls `arch_prctl()` twice would make dynamic functions go 100x slower. We'd have to `__morph_begin()` and friends to rewrite your executable at runtime so Cosmo uses `%gs` instead of `%fs` for TLS. Please note, this issue only impacts x86-64. Aaarch64 is fine. With that said, contributions are welcome since dlopen() isn't high on the priority list.
