### ISSUE TITLE
redbean -d crashes immediately

### ISSUE THREAD

**Issue by cache-return** [jart/cosmopolitan#94]
This occurs for me on Arch Linux.

Output of `./redbean -vv -d`:

```
V2021-03-01T10:22:32.655796:tool/net/redbean.c:1158:redbean:10119] 0.0.0.0:8080 listen
F--------------------000062:tool/net/redbean.c:1124:redbean:10119] 0.0.0.0:8080 accept error EBADF/err=9/errno:9/GetLastError:0

[J[30;101merror[94;49m:tool/net/redbean.c:1124:redbean.com[0m: fatality cachereturn pid 10119
6ffffffffd70 0000004026bf UNKNOWN
6ffffffffd80 00000040acbe UNKNOWN
6ffffffffe60 00000040a89f UNKNOWN
6fffffffff40 00000040942b UNKNOWN
6fffffffff70 000000409770 UNKNOWN
6fffffffffc0 0000004019e3 UNKNOWN
6fffffffffe0 000000401c11 UNKNOWN
7ffc47d2bc10 000000401467 UNKNOWN
```

**Comment by jart** [comment]
Thanks for the report. I've fixed the issue and uploaded a new release. 

For anyone reading, good daemonize flags are as follows:

```
redbean-2021-03-02.com -vv -d -L redbean.log -P redbean.pid
kill -HUP $(cat redbean.pid)
kill -TERM $(cat redbean.pid)
```

Be sure to include the versioned binary name when filing reports.

Also, if you download the .com.dbg file then the backtrace will show you symbols rather than UNKNOWN. You just have to plop it in the same folder.

**Comment by cache-return** [comment]
Confirmed fixed. thanks for the tips and for adding the details to `redbean -h`.
