### ISSUE TITLE
/opt/cosmo/o/third_party/gcc/bin/../libexec/gcc/x86_64-linux-cosmo/11.2.0/as: fork: Resource temporarily unavailable

### ISSUE THREAD

**Issue by kassiansun** [jart/cosmopolitan#950]
Encountered this issue when I was trying `cosmocc --update` on Apple Silicon Sonoma, code checked out from `3.0.2` tag

**Comment by jart** [comment]
Try our latest toolchain. The new toolchain means you're no longer required to to clone / build the mono repo. https://cosmo.zip/pub/cosmocc/cosmocc.zip This will help in your case. You most likely triggered the mono repo's fork() bomb protection. It's probably because your user account is running >2000 processes. If you still want to build the mono repo, you could probably try adding `QUOTA = -P 4000` to your `~/.cosmo.mk`.
