### ISSUE TITLE
"cosmocc -o hello hello.c" makes a ~400kb binary file

### ISSUE THREAD

**Issue by lianjinke** [jart/cosmopolitan#965]
Do we have some way to make a tiny one by cosmocc?

**Comment by jart** [comment]
It's possible to build a non-fat APE binary using cosmocc by using the architecture specific toolchains. For example, say I have:

```c
#include <unistd.h>

int main(int argc, char *argv[]) {
  write(1, "hello\n", 6);
  return 0;
}
```

I can build an APE binary for six OSes on x86-64 as follows:

```
x86_64-unknown-cosmo-cc hello.c -o hello.com.dbg -Os
x86_64-linux-cosmo-objcopy -SO binary hello.com.dbg hello.com
ls -hal hello.com
```

That gives you a binary 164kb in size.

Let's go further. If you check out the mono repo in `MODE=tiny` then you can swap out libcosmo.a with a size optimized version of the C library that excludes features like `--strace` and `--ftrace`. . Assume we have cosmocc installed to `/opt/cosmocc`. Run:

```
make -j8 MODE=tiny toolchain
cp o/tiny/cosmopolitan.a /opt/cosmocc/x86_64-linux-cosmo/lib/libcosmo.a
cp o/tiny/ape/ape*.o /opt/cosmocc/x86_64-linux-cosmo/lib
```

Then build again:

```
x86_64-unknown-cosmo-cc hello.c -o hello.com.dbg -Os
x86_64-linux-cosmo-objcopy -SO binary hello.com.dbg hello.com
ls -hal hello.com
```

And you get a binary 60kb in size. That's about as good as cosmocc can do so far, since it hasn't been size optimized yet.

If you want to drop support for multiple OSes and only build for Linux, then try building a cosmopolitan.a in `MODE=tinylinux`. This appears to be 24kb in size, but a few months ago it was 8kb. I'll take a look into what caused the extra bloat. There's also `MODE=tinynowin` if you want to only support Linux + MacOS + BSD. 

Our goal is to ship these different flavors of toolchains as prebuild zip files so you don't have to build the mono repo. This should happen soon I think.

**Comment by jart** [comment]
With my recent two changes, the `MODE=tiny` version of the cosmocc toolchain should produce a binary more on the order of 32kb for the example given above. 40kb maximum. On the other hand, `MODE=tinylinux` should be ~8kb.

**Comment by lianjinke** [comment]
I see. Thanks for the informative reply. @jart You are a real hacker. Keep going! Looking forward to the prebuild files. I am lazy. :-)
