### ISSUE TITLE
after vfork and closing zipos file, __isfdkind is incorrect

### ISSUE THREAD

**Issue by G4Vi** [jart/cosmopolitan#978]
I made a test:

```c
TEST(zipos, close_after_vfork) {
  if (!IsLinux()) return;
  int zip_fd = open("/zip/life.elf", O_RDONLY);
  ASSERT_NE(-1, zip_fd);
  SPAWN(vfork);
  EXPECT_EQ(1, __isfdkind(zip_fd, kFdZip));
  close(zip_fd);
  int fd = open("/etc/hosts", O_RDONLY);
  ASSERT_NE(-1, fd);
  EXPECT_EQ(0, __isfdkind(fd, kFdZip));
  exit(0);
  EXITS(0);
}
```

Fails on  `EXPECT_EQ(0, __isfdkind(fd, kFdZip));`

@mrdomino could you please take a look? I'm trying to revive https://github.com/jart/cosmopolitan/pull/888 and maintain vfork compat if possible.

**Comment by mrdomino** [comment]
@jart what should happen here? Is it safe to lock `g_fds` after vfork? I'm thinking maybe if `__vforked` then we don't touch refcounts but do clear `g_fds`?

**Comment by mrdomino** [comment]
(No, that probably won't work as such. I'll think about it some more.)

**Comment by jart** [comment]
I would imagine that it is safe to lock a mutex after vfork, provided you unlock it before calling execve().

**Comment by mrdomino** [comment]
Ok, took a bit to look at this.

Looks like the problem is straightforward. `close()` does not call `__releasefd()` if `__vforked`.

The comment says that it wants to avoid locking so `close()` doesn't need to block signals.

So one proposal is: if `__vforked`, have `close()` block signals, lock fds, and call `__releasefd()`.

Unfortunately, this does not work: https://github.com/jart/cosmopolitan/compare/master...0bc5e63d19bb2569aa316f1b3d546cf2a2968415 dies with `nsync panic: attempt to nsync_mu_unlock() an nsync_mu not held in write mode`.

**Comment by jart** [comment]
The only thing `close()` should do when vfork'd is call `sys_close(fd)`. There shouldn't be any need for mutexes or signal masking. The reason why this issue is happening is because the vfork()'d child process appears to be calling __zipos_close() which I assume is modifying the zipos-related data structures in memory. Since the vfork()'d child process shares the same address space as its parent process (including all threads running in the parent process) then once the child dies (after calling execve) and the parent thread resumes execution, the file descriptor is still open in the parent, but the parent's zipos memory says it's closed.

**Comment by G4Vi** [comment]
This is no longer a blocker for the fexecve work. I read about `vfork` and realized it was `vfork` unsafe test setup causing the issue, not the `fexecve` implementation. I rewrote the test to perform the setup before vforking and it's working again.

**Comment by mrdomino** [comment]
I changed the code to not call `__zipos_close` if `__vforked`, but the test case is failing; the test case looks wrong to me now; it shouldn't be opening a new file in the child right?

**Comment by jart** [comment]
Calling something like `open("/dev/null", O_RDWR)` after `vfork()` is not an unreasonable thing to do, in which case the only thing `open()` should do is call `sys_open()`.

**Comment by mrdomino** [comment]
Actually, I just checked, and my commit does not do anything. `__zipos_close` already checks for `!__vforked` prior to freeing the handle.

It looks like it is the case that `open()` is only calling `sys_open()` and `close()` is only calling `sys_close()`.

I wonder if `__isfdkind` should have a special case for `__vforked` that returns 0?

**Comment by jart** [comment]
Yeah I see it now. The test in the original comment is definitely wrong. It doesn't make sense to white-box test `g_fds` memory from within the vfork'd child. The right thing to do here is to test against the public API. You can do that by hard-coding the file descriptor numbers into your test. This is a GOOD thing.

```c
TEST(zipos, close_after_vfork) {
  if (!IsLinux()) return;
  ASSERT_SYS(0, 3, open("/zip/life.elf", O_RDONLY));
  SPAWN(vfork);
  ASSERT_SYS(0, 0, close(3));
  ASSERT_SYS(0, 3, open("/etc/hosts", O_RDONLY));
  ASSERT_SYS(0, 0, close(3));
  ASSERT_SYS(EBADF, -1, close(3));
  EXITS(0);
  ASSERT_SYS(0, 0, close(3));
  ASSERT_SYS(EBADF, -1, close(3));
}
```

That test would much more closely confirm to cosmo's best practices for system call testing.

**Comment by G4Vi** [comment]
> Yeah I see it now. The test in the original comment is definitely wrong. It doesn't make sense to white-box test `g_fds` memory from within the vfork'd child. The right thing to do here is to test against the public API. You can do that by hard-coding the file descriptor numbers into your test. This is a GOOD thing.
> ....
> 
> That test would much more closely conform to cosmo's best practices for system call testing.

Agreed! The original test was an example of an issue with a change to the internal api. There's no guarantees or necessarily need for the internal api to maintain a behavior so it didn't really demonstrate a bug.
