### ISSUE TITLE
More missing math?

### ISSUE THREAD

**Issue by skuzzymiglet** [jart/cosmopolitan#99]
I am attempting to compile [Janet](https://janet-lang.org/) with Cosmopolitan. I am getting these errors:

```
/usr/bin/ld.bfd: /tmp/cc1V4hAf.o: in function `janet_nextafter':
/home/skuzzymiglet/code/jape/all.c:46635: undefined reference to `nextafter'
/usr/bin/ld.bfd: /tmp/cc1V4hAf.o: in function `janet_erf':
/home/skuzzymiglet/code/jape/all.c:46621: undefined reference to `erf'
/usr/bin/ld.bfd: /tmp/cc1V4hAf.o: in function `janet_erfc':
/home/skuzzymiglet/code/jape/all.c:46622: undefined reference to `erfc'
/usr/bin/ld.bfd: /tmp/cc1V4hAf.o: in function `janet_gamma':
```

`erf`, `erfc` and `nextafter` seem to only be in the header

There also seems not to be an `lgamma` function, although it is a C99 feature. So it's probably not a Cosmopolitan problem

**Comment by jart** [comment]
No problem Adding more libm functions or improving the ones we already have is easy to do, since Sun Microsystems and Musl Libc did all the hard work for us. You can download an updated nightly as soon as this issue is marked fixed. Let me know if there's anything else you need. https://justine.lol/cosmopolitan/download.html
